Repository openshift/origin-aggregated-logging, pull requests merged in 2018-11, with the labels that each got.

#1451 logstash:latest is missing - use logstash:5 for compatability
  hack/templates/logstash.yml
Labels: backport/3.10, backport/3.11, component/fluentd, kind/test-flake, lgtm, release/4.0, size/XS

#1454 [3.10] rsyslog fixes and logstash fix for 3.10
  hack/templates/logstash.yml
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/rsyslog-container.service.j2
  hack/testing/rsyslog/rsyslogvar.te
  hack/testing/rsyslog/viaq_formatting.conf
  hack/testing/util.sh
  test/zzz-rsyslog.sh
Labels: component/fluentd, kind/test-flake, lgtm, release/3.10, size/L

#1450 (release-3.11) Bug 1643340 - Fluentd pod should log its logs to /var/log/fluentd/flu…
  fluentd/run.sh
Labels: backport/3.10, lgtm, release/3.11, size/XS

#1457 Bug 1650005 - Fluentd pod should log its logs to /var/log/fluentd/flu…
  fluentd/run.sh
Labels: lgtm, size/XS

#1459 [3.9] backport recent rsyslog test fixes
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/rsyslog-container.service.j2
  hack/testing/rsyslog/rsyslogvar.te
  hack/testing/rsyslog/viaq_formatting.conf
  hack/testing/util.sh
  test/zzz-rsyslog.sh
Labels: kind/test-flake, lgtm, release/3.9, size/L

#1458 Fixes for Mac OS users.
  hack/logging-dump.sh
Labels: lgtm, size/XS

#1463 Dockerfile FROM 5.6.13
  elasticsearch/Dockerfile
Labels: lgtm, size/XS

#1468 source PRIMARY_SHARDS from config map
  elasticsearch/utils/logging
Labels: lgtm, size/XS
