Repository openshift/origin-aggregated-logging, pull requests merged in 2018-12, with the labels that each got.

#1471 Update troubleshooting documentation
  docs/checking-efk-health.md
  docs/troubleshooting.md
Labels: backport/3.11, lgtm, retest-not-required-docs-only, size/L

#1441 LOG-226. Use nonresourceurl for prometheus metrics
  elasticsearch/sgconfig/sg_config.yml
  test/cluster/functionality.sh
Labels: lgtm, release/4.0, size/S

#1478 bug 1652224. Fix defaultIndex for Kibana uprade
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, release/3.11, size/XS

#1482 bug 1656086. remove index-patterns with title=$TITLE
  elasticsearch/init/0510-bz1656086-remove-index-patterns-with-bad-title
  test/0510-bz1656086-remove-index-patterns-with-bad-title
Labels: backport/3.11, lgtm

#1485 bug 1656086. code review fixes
  elasticsearch/init/.0510-bz1656086-remove-index-patterns-with-bad-title.swp
  elasticsearch/init/0510-bz1656086-remove-index-patterns-with-bad-title
  test/0510-bz1656086-remove-index-patterns-with-bad-title
Labels: lgtm, release/3.11, size/S

#1483 add support for SSL_PARTIAL_CHAIN; update fluentd and components
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/configs.d/openshift/filter-k8s-meta.conf
  fluentd/sources
Labels: component/fluentd, lgtm, release/4.0, size/M

#1489 Fix bug 1648453
  curator/Dockerfile
Labels: lgtm, size/XS
