Repository openshift/origin-aggregated-logging, pull requests merged in 2018-02, with the labels that each got.

#940 [release-3.6] Bug 1465039 - fluentd crashes when reading from journald after 3.4 to 3.5 upgrade
  fluentd/Dockerfile.centos7
  fluentd/run.sh
Labels: lgtm, size/XS

#945 [release-3.6] Bug 1534588 - Size of the emitted data exceeds buffer_chunk_limit
  fluentd/run.sh
  test/fluentd-forward.sh
Labels: lgtm, size/L

#946 CI-test: use artifact_out and artifact_log in fluentd-forward.sh.
  test/fluentd-forward.sh
Labels: backport/3.6, backport/3.7, backport/3.8, lgtm, size/M

#937 parse log field for mux minimal mode for json-file logs
  fluentd/run.sh
  test/mux.sh
Labels: backport/3.6, backport/3.7, backport/3.8, component/fluentd, kind/bug, kind/test-flake, lgtm, release/3.9, size/S

#892 1126 es5 dev
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/elasticsearch.repo
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  elasticsearch/install.sh
  elasticsearch/prep-install.origin
  elasticsearch/prep-install.prod
  elasticsearch/probe/readiness.sh
  elasticsearch/run.sh
  elasticsearch/sgconfig/sg_action_groups.yml
  elasticsearch/sgconfig/sg_roles.yml
  elasticsearch/utils/es_seed_acl
  fluentd/lib/fluent-plugin-record-modifier-0.5.0.gem
  fluentd/lib/fluent-plugin-viaq_docker_audit_log_parser-0.0.5.gem
Labels: size/L

#949 fluentd: determine if openshift uses cri-o from nodeconfig
  docs/log-drivers-and-throttling.md
  fluentd/README.md
  fluentd/generate_throttle_configs.rb
  fluentd/run.sh
Labels: lgtm, size/M

#958 Fix `.kibana` regex
  curator/src/curator_cmd.py
Labels: lgtm, size/XS

#966 fix ocp header image downstream
  kibana/Dockerfile
  kibana/logo-OCP-console-hdr-thin.svg
Labels: lgtm, release/3.7, size/M

#967 fix origin kibana image
  kibana/Dockerfile
  kibana/logo-OCP-console-hdr-thin.svg
Labels: lgtm, needs-rebase, release/3.6, size/M

#962 Adding back write permissions to kibana conf dif
  elasticsearch/install.sh
  kibana/install.sh
  kibana/kibana.yml
  test/cluster/functionality.sh
Labels: size/S

#964 bug 1546311. fix ocp image in downstream
  kibana/Dockerfile
  kibana/logo-OCP-console-hdr-thin.svg
Labels: backport/3.6, backport/3.7, backport/completed, lgtm, release/3.9, size/M

#965 Fixes for the fluentd operations tag.
  fluentd/configs.d/filter-post-z-retag-two.conf
  fluentd/configs.d/openshift/output-operations.conf
Labels: lgtm, size/XS

#971 [es5.x] fluentd support for ES 5.x
  fluentd/Dockerfile.centos7
Labels: lgtm, size/XS

#961 Upgrade index mappings and index pattern for ES 5.x
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/common.settings.operations.template.json
  elasticsearch/index_templates/common.settings.project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  hack/update-viaq-data-model.sh
Labels: lgtm, size/XXL

#969 fluentd: fix docs mistake for CRIO_FILE_PATH
  docs/log-drivers-and-throttling.md
Labels: kind/documentation, lgtm, retest-not-required-docs-only, size/XS

#977 Bug 1544815 - logging-fluentd SEGV_ACCERR crash on init when libjemalloc is used in scalability CI lab cluster
  fluentd/run.sh
Labels: area/performance, backport/3.7, backport/3.8, component/fluentd, kind/bug, lgtm, release/3.9, size/XS

#982 turn off MUX_CLIENT_MODE - each test will set as needed
  hack/testing/entrypoint.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
Labels: backport/3.9, kind/test-flake, lgtm, release/3.10, size/S
