Repository openshift/origin-aggregated-logging, pull requests merged in 2018-09, with the labels that each got.

#1334 Document how to manually start cron jobs
  curator/README.md
Labels: lgtm, size/XS

#1329 [release-3.7] add trailing slash for ADD for directories
  elasticsearch/Dockerfile.centos7
  test/zzz-correct-index-names.sh
Labels: size/M

#1300 fluentd duplicate entry test - ensure no open deleted files
  hack/testing/util.sh
  test/zzz-duplicate-entries.sh
Labels: component/fluentd, kind/cleanup, lgtm, release/3.11, size/L

#1338 ignore red cluster when seeding
  elasticsearch/utils/es_seed_acl
Labels: lgtm, release/3.11, size/XS

#1339 bug 1626491. Dont peg replicas to a node for searchguard
  elasticsearch/utils/es_seed_acl
Labels: kind/bug, lgtm, release/3.11

#1340 Fix the wrong link
  docs/quickstart.md
Labels: lgtm, size/XS

#1341 increase default reload_after to 200
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
Labels: area/performance, backport/3.11, component/fluentd, lgtm, release/4.0

#1335 1622822 index patterns
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/init.sh
  elasticsearch/init/0500-remove-index-patterns-without-uid
  elasticsearch/probe/readiness.sh
  hack/testing/test-0500-remove-index-patterns-without-uid
  test/0500-remove-index-patterns-without-uid
  test/cluster/rollout.sh
Labels: backport/3.11, lgtm, release/3.11, size/L

#1347 fix problem with console using internal instead of external hostname
  hack/get-machine-run-tests.sh
Labels: lgtm, size/S

#1314 Use debops framework to deploy viaq configuration.
  hack/testing/rsyslog/README.md
  hack/testing/rsyslog/default_vars.yaml
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/rsyslog/example_vars.yaml
  hack/testing/rsyslog/k8s_container_name.rulebase
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/normalize_level.json
  hack/testing/rsyslog/parse_json.rulebase
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/prio_to_level.json
  hack/testing/rsyslog/roles/openshift_logging_rsyslog/defaults/main.yaml
  hack/testing/rsyslog/roles/openshift_logging_rsyslog/tasks/main.yaml
  hack/testing/rsyslog/roles/openshift_logging_rsyslog/tasks/setup_certs.yaml
  hack/testing/rsyslog/roles/openshift_logging_rsyslog/templates/rsyslog-container.service.j2
  hack/testing/rsyslog/roles/rsyslog/defaults/main.yaml
  hack/testing/rsyslog/roles/rsyslog/handlers/main.yaml
  hack/testing/rsyslog/roles/rsyslog/tasks/main.yaml
  hack/testing/rsyslog/roles/rsyslog/templates/etc/rsyslog.conf.j2
  hack/testing/rsyslog/roles/rsyslog/templates/etc/rsyslog.d/rules.conf.j2
  hack/testing/rsyslog/vars.yaml
  hack/testing/rsyslog/viaq_formatting.conf
  hack/testing/rsyslog/viaq_main.conf
  test/zzz-rsyslog.sh
Labels: area/cda, lgtm, release/4.0, size/XXL

#1351 make tests pass when using crio
  hack/testing/rsyslog/roles/rsyslog/defaults/main.yaml
  test/viaq-data-model.sh
Labels: lgtm, size/S

#1352 handle non-kubernetes containers with journald log driver
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  fluentd/configs.d/openshift/filter-retag-journal.conf
Labels: lgtm, size/M

#1356 Adding sdk_setup script for configuring go path and operator repos
  hack/sdk_setup.sh
Labels: lgtm, size/M

#1362 correct reviewers
  OWNERS
Labels: size/XS

#1364 Bug 1632648 - Record is missing kubernetes field when Docker log driver is journald
  fluentd/run.sh
Labels: backport/3.11, component/fluentd, kind/bug, lgtm, release/4.0, size/XS

#1357 Bug 1554293 - logging-eventrouter event not formatted correctly in El…
  fluentd/configs.d/input-post-forward-mux.conf
  fluentd/run.sh
  test/eventrouter.sh
Labels: backport/3.10, backport/3.11, backport/3.9, component/fluentd, kind/bug, lgtm, release/4.0, size/M

#1350 Including fluent-plugin-concat to support cri-o multiline logs.
  .travis.yml
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/lib/filter_concat/Gemfile
  fluentd/lib/filter_concat/Rakefile
  fluentd/lib/filter_concat/filter_concat.gemspec
  fluentd/lib/filter_concat/lib/filter_concat.rb
  fluentd/lib/filter_concat/test/filter_concat_test.rb
  fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb
  fluentd/lib/generate_throttle_configs/test/generate_throttle_configs_test.rb
Labels: backport/3.11, lgtm, release/4.0, size/L
