Repository openshift/origin-aggregated-logging, pull requests merged in 2018-04, with the labels that each got.

#1031 fix multi_tenancy test to go with SG changes
  elasticsearch/Dockerfile.centos7
  elasticsearch/sgconfig/sg_roles.yml
  elasticsearch/utils/es_load_kibana_ui_objects
  hack/enable-kibana-msearch-access.sh
  kibana/Dockerfile.centos7
  kibana/README.md
  kibana/kibana.yml
  kibana/run.sh
  test/access_control.sh
  test/multi_tenancy.sh
Labels: lgtm, size/L

#955 bz1515715 -- remote syslog hostname
  fluentd/configs.d/openshift/output-operations.conf
  fluentd/out_syslog.rb
  fluentd/out_syslog_buffered.rb
  test/fluentd-forward.sh
  test/remote-syslog.sh
Labels: lgtm, release/3.10, release/3.9, size/XL

#1055 [es5.x] Merge pull request #1006 from jcantrill/1535300
  hack/logging-dump.sh
  hack/testing/check-EFK-running.sh
  hack/testing/entrypoint.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/cucumber/features/kibana.feature
  test/multi_tenancy.sh
  test/pre-upgrade.sh
  test/upgrade.sh
  test/viaq-data-model.sh
Labels: lgtm, size/M

#1056 [release-3.7] reduce test flakes with false hits for ops projects
  hack/testing/templates/test-template.yaml
  test/zzz-correct-index-names.sh
Labels: backport/3.6, kind/test-flake, lgtm, release/3.7, size/L

#1057 fix Dockerfile to use look aside cache
  elasticsearch/.gitignore
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/install.sh
  elasticsearch/lib/elasticsearch-prometheus-exporter/README.md
  elasticsearch/lib/elasticsearch-prometheus-exporter/elasticsearch-prometheus-exporter-2.4.4.1.zip
  elasticsearch/prep-install.prod
  elasticsearch/sources
Labels: lgtm, release/3.10, size/L

#1059 new location for node kubeconfig; dump rsyslog log at end of test
  hack/testing/rsyslog/playbook.yaml
  test/remote-syslog.sh
  test/zzz-rsyslog.sh
Labels: area/cda, backport/3.7, backport/3.9, backport/es5.x, kind/test-flake, lgtm, release/3.10, size/M

#1073 Sort events by timestamp
  hack/logging-dump.sh
Labels: size/XS

#1069 debug access control test
  fluentd/configs.d/filter-pre-mux-client-retag-raw.conf
  fluentd/configs.d/input-post-forward-mux.conf
  fluentd/configs.d/input-post-output.conf
  fluentd/run.sh
  hack/testing/entrypoint.sh
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/util.sh
  test/access_control.sh
  test/mux-client-mode.sh
  test/zzzz-bulk_rejection.sh
Labels: kind/test-flake, lgtm, size/L

#1067 check logging namespace for actual resources
  hack/testing/entrypoint.sh
Labels: backport/3.7, backport/3.9, backport/es5.x, lgtm

#1068 1560778 on 39
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, size/XXL

#1076 bug 1565909. Modify the default operation to be create to avoid delet…
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
Labels: component/fluentd, lgtm, release/3.9, size/XS

#1083 many, many fixes for openshift-logging and related code cleanup
  docs/mux-logging-service.md
  docs/quickstart.md
  fluentd/configs.d/filter-pre-mux-client-retag-raw.conf
  fluentd/configs.d/input-post-forward-mux.conf
  hack/README-dump.md
  hack/branch-deps.spec
  hack/testing/entrypoint.sh
  hack/testing/templates/test-template.yaml
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/rollout.sh
  test/debug_level_logs.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux.sh
  test/pre-upgrade.sh
  test/remote-syslog.sh
  test/upgrade.sh
  test/viaq-data-model.sh
  test/zzz-rsyslog.sh
  test/zzzz-bulk_rejection.sh
Labels: backport/3.6, backport/3.7, backport/3.9, component/fluentd, kind/bug, kind/test-flake, lgtm, release/3.10, size/L

#1077 bug 1565909. Modify the default operation to be create to avoid delet…
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
Labels: backport/3.9, backport/completed, component/fluentd, lgtm, release/3.10

#1082 Modify the check for logging namespace
  hack/logging-dump.sh
Labels: lgtm, size/XS

#1061 fluentd support for ES 5.x
  fluentd/Dockerfile.centos7
Labels: component/fluentd, lgtm, release/3.10, size/XS

#1081 [release-3.9] Fix access-control, mux-client-mode, docker hostmount, other issues
  docs/mux-logging-service.md
  docs/quickstart.md
  fluentd/configs.d/filter-pre-mux-client-retag-raw.conf
  fluentd/configs.d/input-post-forward-mux.conf
  fluentd/configs.d/input-post-output.conf
  fluentd/run.sh
  hack/README-dump.md
  hack/testing/entrypoint.sh
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/templates/test-template.yaml
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/rollout.sh
  test/debug_level_logs.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/pre-upgrade.sh
  test/remote-syslog.sh
  test/upgrade.sh
  test/viaq-data-model.sh
  test/zzz-rsyslog.sh
  test/zzzz-bulk_rejection.sh
Labels: component/fluentd, kind/bug, kind/test-flake, lgtm, release/3.9, size/L

#1088 [es5.x] fix several CI issues; merge with latest master; bulk reject test fixes
  docs/log-drivers-and-throttling.md
  docs/mux-logging-service.md
  docs/quickstart.md
  fluentd/README.md
  fluentd/configs.d/filter-pre-mux-client-retag-raw.conf
  fluentd/configs.d/filter-pre-mux-client.conf
  fluentd/configs.d/input-post-forward-mux.conf
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/user/fluent.conf
  fluentd/configs.d/user/secure-forward.conf
  fluentd/generate_throttle_configs.rb
  fluentd/run.sh
  hack/README-dump.md
  hack/build-images.sh
  hack/logging-dump.sh
  hack/push-release.sh
  hack/testing/entrypoint.sh
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/rsyslog/k8s_container_name.rulebase
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/normalize_level.json
  hack/testing/rsyslog/parse_json.rulebase
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/prio_to_level.json
  hack/testing/rsyslog/rsyslog2es.te
  hack/testing/rsyslog/rsyslog2k8s.te
  hack/testing/rsyslog/rsyslogaccessnssdb.te
  hack/testing/rsyslog/valgrind-rsyslogd
  hack/testing/rsyslog/varlibdockercont.te
  hack/testing/rsyslog/viaq_formatting.conf
  hack/testing/rsyslog/viaq_main.conf
  hack/testing/templates/test-template.yaml
  hack/testing/test-zzz-rsyslog.sh
  hack/testing/test-zzzz-bulk-rejection.sh
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/rollout.sh
  test/debug_level_logs.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/pre-upgrade.sh
  test/remote-syslog.sh
  test/upgrade.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
  test/zzz-rsyslog.sh
  test/zzzz-bulk_rejection.sh
Labels: component/fluentd, kind/bug, kind/test-flake, lgtm, size/XXL

#1063 use look aside cache for curator
  curator/.gitignore
  curator/Dockerfile
  curator/sources
Labels: lgtm, release/3.10, size/M

#1062 support logging-xxx5 images
  hack/build-images.sh
  hack/push-release.sh
Labels: backport/es5.x, lgtm, release/3.10, size/S

#1052 Upgrade to Common Data Model 0.0.14
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: lgtm, size/M

#994 reroute, logs, shards utilities
  elasticsearch/README.md
  elasticsearch/utils/allocate-shard
  elasticsearch/utils/logs
  elasticsearch/utils/move-replica-shard
  elasticsearch/utils/shards
Labels: backport/3.6, backport/3.7, backport/3.9, component/elasticsearch, lgtm, release/3.10, size/L

#1064 Curator continually restarts
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/run.sh
  curator/src/run_cron.py
  curator/src/util.py
Labels: backport/3.7, backport/3.9, backport/es5.x, kind/bug, lgtm, release/3.10, size/L

#1089 make bulk rejection test work with ES5; use es-ops instead of es
  hack/testing/entrypoint.sh
  hack/testing/util.sh
  test/zzzz-bulk_rejection.sh
Labels: backport/3.6, backport/3.7, backport/3.9, kind/test-flake, lgtm, release/3.10, size/L

#1058 use look aside cache for downstream
  kibana/.gitignore
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/README.md
  kibana/prep-install.prod
  kibana/sources
Labels: lgtm, release/3.10, size/M

#1090 skip looking for for project.* indices in check phase
  test/cluster/functionality.sh
Labels: backport/es5.x, kind/test-flake, lgtm, release/3.10, size/XS

#1097 [es5.x] fix bulk monitor; use keyname instead of hardcoded thread_pool
  hack/testing/entrypoint.sh
  test/zzzz-bulk_rejection.sh
Labels: kind/test-flake, lgtm, size/S

#1101 for es5.x only push the es5.x specific images
  hack/push-release.sh
Labels: backport/es5.x, lgtm, retest-not-required, size/S

#1065 Bug 1538560 - [RFE]rename the project name mux-undefined
  docs/mux-logging-service.md
  fluentd/configs.d/input-post-forward-mux.conf
  test/mux.sh
Labels: backport/es5.x, lgtm, size/M

#1106 re-enable bulk rejection test
  Makefile
Labels: lgtm, size/XS

#1114 disable curator test
  Makefile
Labels: lgtm, size/XS

#1122 Sync curator Dockerfile for bad merge to fix bug 1572419
  curator/Dockerfile
Labels: release/3.9

#1112 no way to guarantee fluentd will generate bulk index rejections
  test/zzzz-bulk_rejection.sh
Labels: backport/3.9, backport/es5.x, kind/test-flake, lgtm, release/3.10, size/M

#1111 add guide for troubleshooting CI problems
  README.md
  docs/troubleshooting-ci.md
Labels: area/documentation, kind/documentation, kind/test-flake, lgtm, retest-not-required-docs-only, size/L

#1109 bug 1569825. Turn off JSON parsing by default
  fluentd/README.md
  fluentd/configs.d/openshift/filter-k8s-meta.conf
  fluentd/run.sh
Labels: backport/3.9, backport/es5.x, lgtm, size/S

#1048 bug 1560778. Reduce the number of index-patterns for cluster admins
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: backport/3.9, backport/completed, backport/es5.x, lgtm, size/XS

#1108 bug 1568361. Move ES logs to persistent volume with max backup
  elasticsearch/README.md
  elasticsearch/install.sh
  elasticsearch/lib/openshift-log4jextras/README.md
  elasticsearch/lib/openshift-log4jextras/openshift-log4jextras-0.2.0.jar
  elasticsearch/run.sh
  elasticsearch/utils/es_acl
  elasticsearch/utils/es_seed_acl
  elasticsearch/utils/logs
Labels: backport/3.9, lgtm, release/3.10, size/M

#1116 1546311 on 5
  kibana/Dockerfile
  kibana/logo-OCP-console-hdr-thin.svg
Labels: lgtm, size/S

#1117 update to viaq 0.0.16
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: area/cda, area/documentation, backport/3.6, backport/3.7, backport/3.9, component/elasticsearch, lgtm, release/3.10, size/L

#1129 [release-3.9] update to viaq 0.0.16
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: lgtm, size/L
