Repository openshift/origin-aggregated-logging, pull requests merged in 2018-05, with the labels that each got.

#1118 [es5.x] update to viaq 0.0.16
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: area/cda, area/documentation, backport/es5.x, lgtm, size/L

#1133 fix kibana permissions
  docs/access-control.md
  elasticsearch/.gitignore
  elasticsearch/Dockerfile.centos7
  elasticsearch/sgconfig/sg_action_groups.yml
  elasticsearch/sgconfig/sg_roles.yml
  elasticsearch/sources
Labels: lgtm, size/M

#1110 Adding prometheus plugin and exposing endpoints
  docs/metrics.md
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/configs.d/input-post-forward-mux.conf
  fluentd/configs.d/input-pre-audit-log.conf
  fluentd/configs.d/openshift/input-pre-prometheus-metrics.conf
  fluentd/configs.d/openshift/input-pre-systemd.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/generate_syslog_config.rb
  fluentd/generate_throttle_configs.rb
  hack/testing/check-zzz-fluentd-prometheus-scrape.sh
Labels: lgtm, size/L

#968 Add rawtcp plugin to fluentd
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/out_rawtcp.rb
  hack/templates/logstash.yml
  hack/testing/test-out_rawtcp.sh
  test/out_rawtcp.sh
Labels: component/fluentd, kind/enhancement, lgtm, release/3.10, size/L

#1136 ping doesnt return False, it throws exception
  curator/src/run_cron.py
Labels: lgtm, size/XS

#1134 Bug 1515715 - [RFE]No record generator information in rsyslog server
  fluentd/out_syslog.rb
  fluentd/out_syslog_buffered.rb
  test/remote-syslog.sh
Labels: backport/3.10, backport/3.9, kind/bug, lgtm, release/3.11, size/M

#1155 fluentd must use TLSv1.2 or later to talk to Elasticsearch
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
Labels: backport/3.6, backport/3.7, backport/3.9, backport/es5.x, component/fluentd, kind/bug, lgtm, priority/failing-test, queue/blocks-others, release/3.10, size/XS

#1145 added test indexing_after_ns_removal
  test/indexing_after_ns_removal.sh
Labels: backport/3.9, backport/es5.x, lgtm, size/M

#1162 Set log level on module loggers instead of on root logger
  curator/src/util.py
Labels: backport/3.9, backport/es5.x, lgtm, size/XS

#1153 bump dist-git dockerfiles
  curator/Dockerfile
  elasticsearch/.gitignore
  elasticsearch/Dockerfile
  elasticsearch/sources
  kibana/.gitignore
  kibana/Dockerfile
Labels: lgtm, release/3.10, size/L

#1167 version lock fluent so to still get merge_json feature if needed
  fluentd/Dockerfile.centos7
Labels: backport/3.7, backport/3.9, backport/es5.x, lgtm, release/3.10

#1168 Override index templates on node start even if they already exist
  elasticsearch/run.sh
Labels: backport/3.9, lgtm, size/S

#1154 [release-3.9] oc rollout is unreliable for the error cases - use oc scale to ensure pods are stopped
  test/curator.sh
Labels: backport/3.10, backport/3.6, backport/3.7, backport/es5.x, kind/test-flake, lgtm, release/3.9, size/L

#1176 [es5.x] oc rollout is unreliable for the error cases - use oc scale to ensure pods are stopped
  test/curator.sh
Labels: lgtm, size/L

#1174 fix downstream Dockerfile
  elasticsearch/Dockerfile
  elasticsearch/prep-install.prod
Labels: lgtm, release/3.10

#1178 Version lock fluentd to make sure not to get kube gem that deprecates merge_json
  fluentd/Dockerfile.centos7
Labels: backport/3.9, lgtm, needs-rebase, size/XXL

#1182 only make changes to curator when it is stopped
  test/curator.sh
Labels: backport/3.7, backport/3.9, kind/test-flake, lgtm, release/3.10, size/M

#1181 Fix up for downstream
  elasticsearch/Dockerfile
  elasticsearch/probe/readiness.sh
Labels: component/elasticsearch, lgtm
