Repository openshift/origin-aggregated-logging, pull requests merged in 2018-10, with the labels that each got.

#1367 look for /var/log/fluentd/fluentd.log for pod logs
  hack/testing/util.sh
  test/curator.sh
  test/docker_audit.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/out_rawtcp.sh
  test/read-throttling.sh
  test/remote-syslog.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
  test/zzzz-bulk_rejection.sh
Labels: backport/3.10, backport/3.11, backport/3.9, component/fluentd, kind/test-flake, lgtm, release/4.0, size/L

#1353 Backport of #1336 PR into release-3.10 branch
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/patch/logger/log.rb
  fluentd/patch/logger/supervisor.rb
  fluentd/run.sh
  fluentd/utils/logs
Labels: lgtm, release/3.10, size/XXL

#1363 LOG-192. Impl bearer token for openshift-elasticsearch-plugin
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/run.sh
  elasticsearch/sgconfig/sg_action_groups.yml
  elasticsearch/sgconfig/sg_config.yml
  elasticsearch/sgconfig/sg_roles_mapping.yml
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/kibana_dashboards.sh
  test/multi_tenancy.sh
Labels: backport/3.11, component/elasticsearch, lgtm, release/4.0, size/L

#1371 move fluent utils to /usr/local/bin
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
Labels: backport/3.10, backport/3.11, backport/3.9, lgtm, release/4.0, size/XS

#1354 Backport of #1336 PR into release-3.9 branch
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/patch/logger/log.rb
  fluentd/patch/logger/supervisor.rb
  fluentd/run.sh
  fluentd/utils/logs
Labels: lgtm, size/XXL

#1373 Adding missing $ and making executable
  hack/sdk_setup.sh
Labels: lgtm, size/XS

#1378 Updating to create secret_dir if it doesnt exist for es cert generation
  elasticsearch/utils/logging
Labels: lgtm, size/XS

#1387 allow setting flush_at_shutdown for migration
  fluentd/configs.d/filter-pre-mux-client.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
  fluentd/configs.d/user/secure-forward.conf
Labels: backport/3.10, backport/3.11, backport/3.7, backport/3.9, component/fluentd, kind/enhancement, lgtm, release/4.0, size/XS

#1377 create container.yaml for odcs multi-arch builds
  curator/container.yaml
  elasticsearch/container.yaml
  fluentd/container.yaml
  kibana/container.yaml
Labels: lgtm, size/M

#1389 remove building of logging-auth-proxy
  hack/build-images.sh
  hack/push-release.sh
Labels: release/3.11, size/S

#1388 remove building of logging-auth-proxy
  hack/build-images.sh
  hack/push-release.sh
Labels: backport/3.11, backport/completed, release/4.0, size/S

#1392 rollout test fixes
  test/cluster/rollout.sh
Labels: backport/3.10, backport/3.11, backport/3.7, backport/3.9, kind/cleanup, kind/test-flake, lgtm, release/4.0, size/S

#1394 Use published rpm repos for 3.11 and later; compare_versions function
  hack/get-machine-run-tests.sh
Labels: lgtm, size/L

#1396 add get_all_logging_pod_logs function
  hack/testing/entrypoint.sh
  hack/testing/util.sh
  test/cluster/rollout.sh
Labels: backport/3.10, backport/3.11, backport/3.9, kind/cleanup, kind/test-flake, lgtm, release/4.0, size/M

#1400 [release-3.10] look for /var/log/fluentd/fluentd.log for pod logs
  hack/testing/util.sh
  test/docker_audit.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/out_rawtcp.sh
  test/read-throttling.sh
  test/remote-syslog.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
  test/zzzz-bulk_rejection.sh
Labels: kind/cleanup, kind/test-flake, lgtm, release/3.10, size/L

#1355 Back port of #1336 PR into release-3.11 branch
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/patch/logger/log.rb
  fluentd/patch/logger/supervisor.rb
  fluentd/run.sh
  fluentd/utils/logs
Labels: lgtm, release/3.11, size/XXL

#1366 Added info message about redirection of fluentd logs
  fluentd/run.sh
  hack/logging-dump.sh
Labels: backport/3.11, backport/3.9, lgtm, release/4.0, size/S

#1398 [release-3.9] allow setting flush_at_shutdown for migration
  fluentd/configs.d/filter-pre-mux-client.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
  fluentd/configs.d/user/secure-forward.conf
Labels: component/fluentd, kind/feature, lgtm, release/3.9, size/S

#1397 [release-3.10] allow setting flush_at_shutdown for migration
  fluentd/configs.d/filter-pre-mux-client.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
  fluentd/configs.d/user/secure-forward.conf
Labels: component/fluentd, kind/feature, lgtm, release/3.10, size/S

#1401 [release-3.9] look for /var/log/fluentd/fluentd.log for pod logs
  hack/testing/util.sh
  test/docker_audit.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/read-throttling.sh
  test/remote-syslog.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
  test/zzzz-bulk_rejection.sh
Labels: kind/cleanup, kind/test-flake, lgtm, release/3.9, size/L

#1386 [release-3.11] Including fluent-plugin-concat to support cri-o multiline logs.
  .travis.yml
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/lib/filter_concat/Gemfile
  fluentd/lib/filter_concat/Rakefile
  fluentd/lib/filter_concat/filter_concat.gemspec
  fluentd/lib/filter_concat/lib/filter_concat.rb
  fluentd/lib/filter_concat/test/filter_concat_test.rb
  fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb
  fluentd/lib/generate_throttle_configs/test/generate_throttle_configs_test.rb
Labels: lgtm, release/3.11, size/L

#1399 Fix bulk rejection test
  test/zzzz-bulk_rejection.sh
Labels: lgtm, release/3.11, size/S

#1390 bug 1627086. Add configuration to disable Netty recycler
  elasticsearch/run.sh
Labels: backport/3.11, component/elasticsearch, lgtm, release/4.0, size/XS

#1412 [3.10] move utils to /usr/local/bin
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
Labels: kind/feature, lgtm, release/3.10, size/XS

#1415 [3.9] rollout test fixes
  test/cluster/rollout.sh
Labels: kind/test-flake, lgtm, release/3.9, size/M

#1370 LOG-192. Impl bearer token for openshift-elasticsearch-plugin
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/run.sh
  elasticsearch/sgconfig/sg_action_groups.yml
  elasticsearch/sgconfig/sg_config.yml
  elasticsearch/sgconfig/sg_roles_mapping.yml
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/kibana_dashboards.sh
  test/multi_tenancy.sh
Labels: lgtm, release/3.11, size/L

#1417 [3.7] turn off mux for 3.7 eventrouter test
  test/eventrouter.sh
Labels: kind/test-flake, lgtm, release/3.7

#1411 [3.9] move utils to /usr/local/bin
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
Labels: kind/feature, lgtm, release/3.9, size/XS

#1128 [release-3.7] update to viaq 0.0.16
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: lgtm, release/3.7, size/L

#1410 more rollout test fixes
  test/cluster/rollout.sh
Labels: backport/3.10, backport/3.11, backport/3.7, backport/3.9, kind/test-flake, lgtm, release/4.0, size/XS

#1414 [release-3.10] rollout test fixes
  test/cluster/rollout.sh
Labels: kind/test-flake, lgtm, release/3.10, size/M

#1402 [release-3.7] look for /var/log/fluentd/fluentd.log for pod logs
  hack/testing/util.sh
  test/docker_audit.sh
  test/fluentd-forward.sh
  test/json-parsing.sh
  test/mux-client-mode.sh
  test/mux.sh
  test/read-throttling.sh
  test/remote-syslog.sh
  test/viaq-data-model.sh
  test/zzz-correct-index-names.sh
Labels: kind/cleanup, kind/test-flake, lgtm, release/3.7, size/L

#1419 [3.11] move utils to /usr/local/bin
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
Labels: kind/feature, lgtm, release/3.11

#1372 fix delete_by_query in kibana
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/prep-install.origin
Labels: backport/3.11, lgtm, release/4.0, size/S

#1425 fix recent eventrouter and fluentd-forward test flakes
  hack/testing/util.sh
  test/eventrouter.sh
  test/fluentd-forward.sh
Labels: backport/3.11, kind/test-flake, lgtm, release/4.0, size/M

#1431 fix typos and enhance diagnosing failures
  hack/testing/util.sh
  test/fluentd-forward.sh
Labels: kind/test-flake, lgtm, release/4.0, size/M

#1432 [3.11] fix recent eventrouter and fluentd-forward test flakes
  hack/testing/util.sh
  test/eventrouter.sh
  test/fluentd-forward.sh
Labels: kind/test-flake, lgtm, release/3.11, size/L

#1424 Bug 1613722 - Eventrouter creates duplicated events every 30 min with…
  .travis.yml
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/lib/filter_elasticsearch_genid_ext/Gemfile
  fluentd/lib/filter_elasticsearch_genid_ext/Rakefile
  fluentd/lib/filter_elasticsearch_genid_ext/filter_elasticsearch_genid_ext.gemspec
  fluentd/lib/filter_elasticsearch_genid_ext/lib/filter_elasticsearch_genid_ext.rb
  fluentd/lib/filter_elasticsearch_genid_ext/test/filter_elasticsearch_genid_ext_test.rb
  test/eventrouter.sh
Labels: backport/3.10, backport/3.11, lgtm, release/4.0, size/L

#1433 Fixing prometheus plugin certs to use env vars like output plugin
  fluentd/configs.d/openshift/input-pre-prometheus-metrics.conf
Labels: lgtm, size/XS

#1434 Bug 1613722 - Eventrouter creates duplicated events every 30 min with…
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/lib/filter_elasticsearch_genid_ext/test/filter_elasticsearch_genid_ext_test.rb
Labels: backport/3.10, backport/3.11, lgtm, size/S

#1435 add support for rsyslog collector access control
  elasticsearch/sgconfig/sg_roles.yml
  elasticsearch/sgconfig/sg_roles_mapping.yml
Labels: backport/3.11, component/elasticsearch, kind/feature, lgtm, release/4.0, size/S

#1436 [3.11] Bug 1613722 - Eventrouter creates duplicated events every 30 min with…
  .travis.yml
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/lib/filter_elasticsearch_genid_ext/Gemfile
  fluentd/lib/filter_elasticsearch_genid_ext/Rakefile
  fluentd/lib/filter_elasticsearch_genid_ext/filter_elasticsearch_genid_ext.gemspec
  fluentd/lib/filter_elasticsearch_genid_ext/lib/filter_elasticsearch_genid_ext.rb
  fluentd/lib/filter_elasticsearch_genid_ext/test/filter_elasticsearch_genid_ext_test.rb
  test/eventrouter.sh
Labels: lgtm, release/3.11, size/L

#1439 [3.11] Bug 1613722 - Eventrouter creates duplicated events every 30 min with…
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/lib/filter_elasticsearch_genid_ext/test/filter_elasticsearch_genid_ext_test.rb
Labels: lgtm, release/3.11, size/S

#1437 [3.10] Bug 1641166 - Eventrouter creates duplicated events every 30 min with…
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/filter_elasticsearch_genid_ext.rb
  test/eventrouter.sh
Labels: lgtm, release/3.10, size/L

#1444 revert curator to 5.2.0 because of missing downstream dependencies
  curator/Dockerfile
  curator/Dockerfile.centos7
Labels: backport/3.11, lgtm, release/4.0, size/XS
