Repository openshift/origin-aggregated-logging, pull requests merged in 2018-07, with the labels that each got.

#1177 Relies on single SG index
  docs/checking-efk-health.md
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/prep-install.origin
Labels: lgtm, release/3.11, size/M

#1231 remove discovery plugin
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/prep-install.origin
  test/cluster/functionality.sh
Labels: component/elasticsearch, lgtm, release/3.11, size/S

#1232 sync downstream es with upstream for openshift-elasticsearch-plugin-5.…
  elasticsearch/.gitignore
  elasticsearch/sources
Labels: component/elasticsearch, lgtm, release/3.11, size/XS

#1236 Appending / to ADD lines in ES dockerfiles
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, size/XS

#1237 Appending / to ADD lines in ES dockerfiles
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, size/XS

#1239 Update downstream to be based on rpms
  curator/Dockerfile
  curator/sources
Labels: release/3.11, size/S

#1240 Adding prometheus plugin, sources, and exposing endpoints
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/configs.d/openshift/input-pre-prometheus-metrics.conf
  fluentd/run.sh
  hack/testing/check-zzz-fluentd-prometheus-scrape.sh
Labels: lgtm, release/3.11, size/M

#1224 Reenabling prometheus metrics functionality test
  elasticsearch/sgconfig/sg_action_groups.yml
  hack/testing/util.sh
  test/cluster/functionality.sh
Labels: lgtm, size/M

#1246 more test fixes and debug remote-syslog flakes
  hack/get-machine-run-tests.sh
  hack/testing/util.sh
  test/access_control.sh
  test/read-throttling.sh
  test/remote-syslog.sh
Labels: lgtm, size/L

#1248 Fixing unbound var in our test
  hack/testing/util.sh
Labels: lgtm, size/XS

#1243 allow es to build against an es base image
  elasticsearch/Dockerfile
  elasticsearch/install.sh
  elasticsearch/prep-install.prod
  elasticsearch/run.sh
Labels: lgtm, size/M

#1244 Modify the check for logging namespace
  hack/logging-dump.sh
Labels: lgtm, size/XS

#1249 allow rsyslog from rpm install or image
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/rsyslogvar.te
  hack/testing/rsyslog/viaq_formatting.conf
  test/zzz-rsyslog.sh
Labels: lgtm, release/3.11, size/M

#1254 allow deploying rsyslog in a multi-node deployment
  hack/testing/rsyslog/playbook.yaml
  test/zzz-rsyslog.sh
Labels: kind/test-flake, lgtm, release/3.11, size/L

#1253 add back prep-install.prod
  elasticsearch/Dockerfile
  elasticsearch/prep-install.prod
Labels: component/elasticsearch, lgtm, release/3.11, size/XS

#1255 master now requires ansible-2.6
  hack/get-machine-run-tests.sh
Labels: kind/test-flake, lgtm, release/3.11, size/S

#1252 Updating ES to create jks files upon start up if not present in secret dir
  elasticsearch/run.sh
Labels: lgtm, size/M

#1259 add support for rsyslog bulk index retry
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/rsyslog/playbook.yaml
Labels: lgtm, release/3.11, size/L

#1261 parse embedded json in log/MESSAGE fields
  hack/testing/rsyslog/k8s_container_name.rulebase
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/parse_json.rulebase
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/viaq_formatting.conf
Labels: lgtm, release/3.11, size/L

#1265 Reuse env var in Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, size/XS

#1228 bug 1596099. Use IndexRequest instead of UpdateRequest
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/prep-install.origin
Labels: backport/3.7, backport/3.9, lgtm, release/3.10, size/S
