Repository openshift/origin-aggregated-logging, pull requests merged in 2018-06, with the labels that each got.

#1187 better describe error situations
  curator/src/run_cron.py
  curator/src/util.py
Labels: lgtm, size/M

#1189 mapper.allow_dots_in_name setting not needed (supported) in ES 5.x
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: lgtm, size/XS

#1195 fix logs util to retrieve logs from persistent dir. Ref #1108
  elasticsearch/utils/logs
Labels: component/elasticsearch, kind/bug, lgtm, release/3.11, size/XS

#1193 bug 1584665. Remove prometheus plugin
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/configs.d/openshift/input-pre-prometheus-metrics.conf
  hack/testing/check-zzz-fluentd-prometheus-scrape.sh
Labels: component/fluentd, lgtm, release/3.10, size/M

#1198 gather more debugging; reduce flakes
  test/remote-syslog.sh
Labels: backport/3.7, backport/3.9, backport/es5.x, kind/test-flake, lgtm, release/3.10, size/L

#1201 add script to provision machine and run tests
  hack/get-machine-run-tests.sh
Labels: backport/3.9, backport/es5.x, kind/test-flake, release/3.10, size/XL

#1203 fix test failures
  hack/get-machine-run-tests.sh
Labels: lgtm, size/M

#1202 convert remote-syslog test to use standard test func; get more info when entries are not in es
  hack/testing/entrypoint.sh
  hack/testing/util.sh
  test/remote-syslog.sh
Labels: backport/3.7, backport/3.9, backport/es5.x, kind/test-flake, lgtm, release/3.10, size/L

#1206 convert remote-syslog test to use standard test func; get more info when entries are not in es
  hack/get-machine-run-tests.sh
Labels: lgtm, size/M

#1194 bug 1582232. Disable shard allocation for searchguard
  elasticsearch/run.sh
  elasticsearch/utils/es_seed_acl
Labels: backport/3.9, component/elasticsearch, kind/bug, lgtm, release/3.10, size/M

#1208 1589905 kibana timeout
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/README.md
  kibana/kibana.yml
  kibana/run.sh
  kibana/utils
Labels: needs-rebase, release/3.6, size/L

#1074 Adding tests to verify rolled journald files are released
  hack/testing/entrypoint.sh
  hack/testing/test-zzz-duplicate-entries.sh
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/curator.sh
  test/docker_audit.sh
  test/eventrouter.sh
  test/kibana_dashboards.sh
  test/multi_tenancy.sh
  test/mux.sh
  test/upgrade.sh
  test/utf8-characters.sh
  test/zzz-correct-index-names.sh
  test/zzz-duplicate-entries.sh
  test/zzzz-bulk_rejection.sh
Labels: lgtm, size/XL

#1070 bug 1562004. Provide utility to sanitize chunks
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/README.md
  fluentd/utils/sanitize_msg_chunks
Labels: lgtm, size/L

#1211 Bug 1588416 - should fetch log from /elasticsearch/persistent/logging…
  hack/logging-dump.sh
Labels: backport/3.10, backport/3.9, lgtm, size/S

#1158 [release-3.7] fluentd must use TLSv1.2 or later to talk to Elasticsearch
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
Labels: release/3.7, size/XS

#1210 [es5.x] Adding test to check for duplicate records with fluentd and journald …
  hack/testing/entrypoint.sh
  hack/testing/test-zzz-duplicate-entries.sh
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/curator.sh
  test/docker_audit.sh
  test/eventrouter.sh
  test/kibana_dashboards.sh
  test/multi_tenancy.sh
  test/mux.sh
  test/upgrade.sh
  test/utf8-characters.sh
  test/zzz-correct-index-names.sh
  test/zzz-duplicate-entries.sh
  test/zzzz-bulk_rejection.sh
Labels: lgtm, size/XL

#1209 [release-3.9] Adding test to check for duplicate records with fluentd and journald …
  hack/testing/entrypoint.sh
  hack/testing/test-zzz-duplicate-entries.sh
  hack/testing/util.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/curator.sh
  test/docker_audit.sh
  test/eventrouter.sh
  test/kibana_dashboards.sh
  test/multi_tenancy.sh
  test/mux.sh
  test/upgrade.sh
  test/utf8-characters.sh
  test/zzz-correct-index-names.sh
  test/zzz-duplicate-entries.sh
  test/zzzz-bulk_rejection.sh
Labels: lgtm, release/3.9, size/XL

#1216 Update readme to identify this as an inactive branch
  README.md
Labels: release/3.11, size/XS

#1217 cannot have empty field name in es5
  test/viaq-data-model.sh
Labels: kind/test-flake, release/3.11, size/XS

#1218 Fixing date option for hack/testing/util
  hack/testing/util.sh
Labels: lgtm, size/XS

#1220 Fixing merge from 5x branch to master for multi_tenancy test
  test/multi_tenancy.sh
Labels: lgtm, size/S

#1219 emptyvalue not emptyfield
  test/viaq-data-model.sh
Labels: size/XS

#1221 ansible package name changed - drops the .el7
  hack/get-machine-run-tests.sh
Labels: lgtm, size/XS

#1222 fix downstream to depend on rpm
  kibana/Dockerfile
  kibana/install.sh
  kibana/sources
Labels: component/kibana, lgtm, release/3.11, size/S

#1227 sync Docker and Docker.centos7 to fix image job
  kibana/Dockerfile.centos7
Labels: lgtm, size/XS

#1183 add fluentd unit tests
  .travis.yml
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/lib/generate_throttle_configs/Rakefile
  fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb
  fluentd/lib/generate_throttle_configs/test/generate_throttle_configs_test.rb
  fluentd/lib/generate_throttle_configs/test/test_helper.rb
Labels: component/fluentd, lgtm, size/L

#1159 [release-3.6] fluentd must use TLSv1.2 or later to talk to Elasticsearch
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
Labels: release/3.6, size/XS
