Repository openshift/origin-aggregated-logging, pull requests merged in 2018-03, with the labels that each got.

#933 add bulk index rejection test
  hack/testing/test-zzzz-bulk-rejection.sh
  hack/testing/util.sh
  test/zzz-correct-index-names.sh
  test/zzzz-bulk_rejection.sh
Labels: backport/3.7, backport/3.8, backport/3.9, component/fluentd, lgtm, release/3.9, size/L

#974 Generate uuid on ingestion to reduce duplicates
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/user/fluent.conf
  test/fluentd-forward.sh
Labels: backport/3.6, backport/3.7, backport/3.9, lgtm, release/3.9, size/S

#988 Bug 1548720 - fluent-plugin-secure-forward couldn't read the Environment ${HOSTNAME}
  fluentd/configs.d/filter-pre-mux-client.conf
  fluentd/configs.d/user/secure-forward.conf
Labels: lgtm, release/3.9, size/XS

#999 add branch deps
  hack/branch-deps.spec
Labels: backport/3.6, backport/3.7, kind/test-flake, release/3.9, size/M

#995 Bug 1550842 - Embed json logs when using cri-o
  fluentd/generate_throttle_configs.rb
Labels: size/XS

#1003 Upgrade to common data model 0.0.13 for release 3.9
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  hack/update-viaq-data-model.sh
Labels: backport/3.9, size/XL

#993 Docker audit test flake
  test/docker_audit.sh
Labels: size/M

#1008 remove CONTAINER_TAG field
  test/viaq-data-model.sh
Labels: backport/3.6, backport/3.7, backport/3.9, kind/test-flake, lgtm, release/3.10, size/XS

#1001 Upgrade common data model to 0.0.13 for release 3.6
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  hack/update-viaq-data-model.sh
Labels: backport/3.6, lgtm, size/XL

#973 Upgrade common data model to 0.0.13 for release 3.7
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  hack/update-viaq-data-model.sh
Labels: backport/3.7, lgtm, size/XL

#989 [release-3.6] backport several fixes to 3.6 to make cherrypicks possible/easier
  curator/run_cron.py
  elasticsearch/Dockerfile.centos7
  elasticsearch/sgconfig/sg_action_groups.yml
  hack/testing/util.sh
  test/cluster/functionality.sh
  test/mux.sh
  test/utf8-characters.sh
Labels: kind/test-flake, lgtm, release/3.6, size/M

#981 update components - use released versions of gems rather than vendored
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/lib/fluent-plugin-record-modifier-0.5.0.gem
Labels: component/fluentd, kind/enhancement, lgtm, release/3.6

#998 use -c elasticsearch
  hack/enable-kibana-msearch-access.sh
Labels: backport/3.6, backport/3.7, backport/3.9, kind/test-flake, lgtm, release/3.10

#1016 Removing an unnecessary line from the rebase mistake in pr/#926.
  test/fluentd-forward.sh
Labels: backport/3.6, backport/3.7, backport/3.8, backport/3.9, kind/test-flake, lgtm, release/3.10, size/XS

#1007 Shard operations indices
  elasticsearch/index_templates/com.redhat.viaq-openshift-orphaned.template.json
  elasticsearch/index_templates/common.settings.operations.orphaned.json
  elasticsearch/index_templates/common.settings.operations.template.json
  elasticsearch/run.sh
Labels: backport/3.7, backport/3.9, component/elasticsearch, kind/bug, lgtm, release/3.10, size/XL

#1004 Upgrade to common data model 0.0.13
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  hack/update-viaq-data-model.sh
Labels: lgtm, size/XL

#975 Addressing CI issues
  elasticsearch/utils/es_acl
  hack/testing/check-EFK-running.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/cluster/rollout.sh
  test/curator.sh
Labels: size/M

#1022 ES5 disallows empty field names
  hack/testing/test-viaq-data-model.py
  test/viaq-data-model.sh
Labels: backport/es5.x, kind/test-flake, lgtm, size/XS

#1023 gather more information when docker_audit test fails
  test/docker_audit.sh
Labels: backport/3.7, backport/3.9, backport/es5.x, kind/test-flake, lgtm, release/3.10, size/M

#1021 Take both forward and secure_forward into account for NUM_OUTPUTS
  fluentd/run.sh
Labels: backport/1.5, backport/3.6, backport/3.7, backport/3.9, backport/es5.x, component/fluentd, kind/bug, lgtm, needs-ok-to-test, release/3.10, size/XS

#1006 Modify the default project namespace
  hack/enable-kibana-msearch-access.sh
  hack/logging-dump.sh
  hack/testing/check-EFK-running.sh
  hack/testing/entrypoint.sh
  test/access_control.sh
  test/cluster/functionality.sh
  test/cucumber/features/kibana.feature
  test/multi_tenancy.sh
  test/pre-upgrade.sh
  test/upgrade.sh
  test/viaq-data-model.sh
  test/zzzz-bulk_rejection.sh
Labels: backport/3.9, lgtm, release/3.10, size/M

#1020 Upgrade curator to v5.2
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/README.md
  curator/lib/oalconverter/__init__.py
  curator/lib/oalconverter/convert.py
  curator/lib/oalconverter/parser.py
  curator/lib/oalconverter/util.py
  curator/run.sh
  curator/setup.cfg
  curator/setup.py
  curator/src/curator_cmd.py
  curator/src/run_cron.py
  curator/src/util.py
  curator/test/__init__.py
  curator/test/basic-cfg-result.yaml
  curator/test/basic-cfg.yaml
  curator/test/empty-cfg-result.yaml
  curator/test/empty-cfg.yaml
  curator/test/name-invalid-cfg.yaml
  curator/test/name-too-long-cfg.yaml
  curator/test/regex-cfg-result.yaml
  curator/test/regex-cfg.yaml
  curator/test/test_converter.py
  hack/testing/util.sh
  test/cluster/rollout.sh
  test/curator.sh
Labels: size/XXL

#1034 Updating default run time for curator
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/run.sh
Labels: lgtm, size/S

#1032 rsyslog testing - test k8s, es tls, viaq formatting
  hack/testing/rsyslog/elasticsearch.conf.j2
  hack/testing/rsyslog/k8s_container_name.rulebase
  hack/testing/rsyslog/k8s_filename.rulebase
  hack/testing/rsyslog/mmk8s.conf.j2
  hack/testing/rsyslog/normalize_level.json
  hack/testing/rsyslog/parse_json.rulebase
  hack/testing/rsyslog/playbook.yaml
  hack/testing/rsyslog/prio_to_level.json
  hack/testing/rsyslog/rsyslog2es.te
  hack/testing/rsyslog/rsyslog2k8s.te
  hack/testing/rsyslog/rsyslogaccessnssdb.te
  hack/testing/rsyslog/valgrind-rsyslogd
  hack/testing/rsyslog/varlibdockercont.te
  hack/testing/rsyslog/viaq_formatting.conf
  hack/testing/rsyslog/viaq_main.conf
  hack/testing/test-zzz-rsyslog.sh
  test/zzz-rsyslog.sh
Labels: area/cda, backport/3.9, kind/enhancement, lgtm, release/3.10, size/XL
