Repository openshift/origin-aggregated-logging, pull requests merged in 2019-11, with the labels that each got.

#1781 disable tests broken by logforwarding
  hack/testing/entrypoint.sh
Labels: approved, kind/failing-test, lgtm, release/4.3, size/XS

#1782 Increased go version for setup script
  hack/sdk_setup.sh
Labels: approved, kind/cleanup, lgtm, release/4.3, size/XS

#1780 improvements to hack/build-images.sh
  hack/build-images.sh
Labels: approved, kind/cleanup, lgtm, release/4.3, size/M

#1783 exclude tests for unsupported features
  Makefile
  hack/testing/entrypoint.sh
Labels: approved, kind/cleanup, lgtm, release/4.3, size/S

#1776 Take into account .audit index in curator
  curator/lib/oalconverter/convert.py
Labels: approved, component/curator, kind/feature, lgtm, release/4.3, size/XS

#1786 Bug 1748478: Add more states to init probe
  elasticsearch/init.sh
  elasticsearch/probe/readiness.sh
Labels: approved, kind/bug, lgtm, release/4.3

#1788 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1779 Bug 1765646: Fluentd single pod logging performance regression 3.x
  fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb
  fluentd/lib/generate_throttle_configs/test/generate_throttle_configs_test.rb
Labels: approved, area/performance, autoretest, bugzilla/valid-bug, component/fluentd, kind/bug, lgtm, priority/critical-urgent, release-note-action-required, release/3.11, size/M

#1789 allow specifying the installer url
  hack/deploy-openshift-cluster.sh
Labels: approved, kind/cleanup, lgtm, release/4.3, size/XS

#1790 LOG-535 - Add IPv6 support to fluentd plugins
  fluentd/out_syslog.rb
Labels: approved, component/fluentd, kind/feature, lgtm, release/4.3, size/XS
