Repository openshift/origin-aggregated-logging, pull requests merged in 2019-12, with the labels that each got.

#1791 use custom image tag when pushing too
  hack/build-images.sh
Labels: approved, es6x, kind/cleanup, lgtm

#1794 [release-4.1] fix the way we look up ci images
  hack/deploy-logging-marketplace.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/failing-test, lgtm, release/4.1, size/M

#1796 fix recent CI failures
  hack/deploy-logging.sh
Labels: approved, kind/flake, lgtm, release/4.4, size/S

#1798 Actually run unit tests for fluentd
  test/unit/Dockerfile
Labels: approved, lgtm, release/4.4, size/XS

#1785 Bug 1762572: Bump openshift-elasticsearch-plugin
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, backport/3.11, backport/4.1, backport/4.2, backport/4.3, bugzilla/valid-bug, component/elasticsearch, kind/bug, lgtm, release/4.4, size/XS

#1804 use operators.coreos.com/v1; handle multiple manifests versions
  hack/deploy-logging.sh
  hack/vendor/olm-test-script/operatorgroup-allnamespaces-template.yaml
  hack/vendor/olm-test-script/operatorgroup-template.yaml
  hack/vendor/olm-test-script/operatorgroup.yaml
Labels: approved, kind/failing-test, lgtm, priority/critical-urgent, release/4.4, size/S

#1806 Upgrade model to 2019.12.16.0
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: approved, lgtm, size/L

#1809 fix ci for 4.3 - use release-4.3 branch for eo and clo
  hack/deploy-logging.sh
  hack/vendor/olm-test-script/operatorgroup-allnamespaces-template.yaml
  hack/vendor/olm-test-script/operatorgroup-template.yaml
  hack/vendor/olm-test-script/operatorgroup.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/failing-test, lgtm, release/4.3, size/S
