Repository openshift/origin-aggregated-logging, pull requests merged in 2019-07, with the labels that each got.

#1683 Bug 1705589. Consume newer version of plugin to mitigate blank page
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/sgconfig/sg_action_groups.yml
Labels: autoretest, backport/3.11, backport/4.1, component/elasticsearch, kind/bug, lgtm, release/4.2

#1650 bug 1705589. Consume newer version of plugin to mitigate blank page
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/sgconfig/sg_action_groups.yml
Labels: lgtm, release/3.11, size/S

#1671 LOG-372 - rsyslog - support improved undefined field handling
  hack/build-images.sh
  rsyslog/Dockerfile
  rsyslog/undefined_field/undefined_field.go
Labels: lgtm, size/L

#1662 Bug 1666167 - Updating to allow the EO to be authorized as sg_role_admin if presenting its SA token
  elasticsearch/sgconfig/sg_config.yml
  elasticsearch/sgconfig/sg_roles_mapping.yml
Labels: lgtm, size/XS

#1688 Bug 1719733: Export and import scripts for kibana objects
  elasticsearch/README.md
  elasticsearch/utils/export-kibana-objects
  elasticsearch/utils/import-kibana-objects
Labels: backport/master-post-release, lgtm, release/3.11, size/L

#1691 Bug 1728856: Fix prometheus metrics visibility
  elasticsearch/sgconfig/sg_config.yml
  hack/testing/test-es-metrics-access.sh
  test/verify-es-metrics-access.sh
Labels: autoretest, cherry-pick-to/master, component/elasticsearch, kind/bug, lgtm, release/3.11

#1692 Add cronjobs to logging-dump script
  hack/logging-dump.sh
Labels: lgtm, size/XS

#1689 deploy es with storage and multi-nodes for upgrade testing
  hack/deploy-logging.sh
  hack/testing/util.sh
  openshift/ci-operator/build-image/cr.yaml
  test/cluster/functionality.sh
  test/zzzz-bulk_rejection.sh
Labels: autoretest, lgtm, release/4.2, size/M

#1695 Bug 1729297: Add authentication config to properly check SAR for addi…
  elasticsearch/sgconfig/sg_config.yml
  hack/testing/test-es-metrics-access.sh
  test/verify-es-metrics-access.sh
Labels: backport/4.1, bugzilla/valid-bug, lgtm, release/4.2, size/M

#1702 Bug 1715370: Some orphaned logs sent to .operations.* index
  fluentd/run.sh
Labels: bugzilla/valid-bug, lgtm, size/XS

#1704 imagePullPolicy Always - ensure admin user
  hack/build-images.sh
  hack/deploy-logging.sh
  hack/test-logging.sh
Labels: kind/test-flake, lgtm, release/4.2, size/L

#1701 Bug 1730588: openshift-elasticsearch-plugin-5.6.13.8
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: backport/3.11, backport/4.1, bugzilla/valid-bug, lgtm, release/4.2, size/XS

#1705 LOG-425. Add container to test items formally tested by travis
  .travis.yml
  test/unit/Dockerfile
Labels: lgtm, size/M

#1685 LOG-372 - rsyslog - support improved undefined field handling
  hack/testing/test-viaq-data-model.py
  hack/testing/util.sh
  openshift/ci-operator/build-image/Dockerfile.full
  rsyslog/README.md
  rsyslog/undefined_field/undefined_field.go
  rsyslog/undefined_field/undefined_field_test.go
  rsyslog/utils/logs
  test/viaq-data-model.sh
  test/zzz-rsyslog.sh
Labels: autoretest, component/rsyslog, kind/feature, lgtm, release/4.2, size/XXL

#1708 LOG-425. Add run for testing
  test/unit/Dockerfile
  test/unit/run.sh
Labels: lgtm, size/S

#1706 update logging-dump script for 4.x
  hack/logging-dump.sh
  test/unit/Dockerfile
Labels: lgtm, release/4.2, size/L

#1700 Bug 1731855: Add jaeger permissions to create ES templates
  elasticsearch/sgconfig/sg_roles.yml
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, release/4.1, size/XS

#1645 Precreate indicies documentation
  docs/troubleshooting.md
Labels: area/documentation, component/elasticsearch, kind/documentation, lgtm, release/3.11, retest-not-required-docs-only, size/L

#1713 Bug 1730652: Rsyslog prometheus stats not being reported correctly.
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/exporter.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/exporter_test.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/imjournal.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/imjournal_test.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/mmkubernetes.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/mmkubernetes_test.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/omelasticsearch.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/omelasticsearch_test.go
  rsyslog/go/src/github.com/soundcloud/rsyslog_exporter/utils.go
  test/zzz-rsyslog.sh
Labels: approved, autoretest, bugzilla/valid-bug, component/rsyslog, kind/bug, lgtm, release/4.2, size/XXL

#1712 Bug 1734080: Add jaeger index templates
  elasticsearch/index_templates/jaeger-service.json
  elasticsearch/index_templates/jaeger-span.json
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, release/4.2, size/L

#1710 Bug 1733011: Inappropriate message when view rsyslog pod logs by `oc…
  rsyslog/utils/logs
  test/zzz-rsyslog.sh
Labels: approved, lgtm, release/4.2, size/S
