Repository openshift/origin-aggregated-logging, pull requests merged in 2019-09, with the labels that each got.

#1735 Bug 1738411: Bump openshift-elasticsearch-client to 5.6.13.10
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  hack/testing/util.sh
  test/access_control.sh
Labels: approved, backport/3.11, backport/4.1, bugzilla/valid-bug, component/elasticsearch, kind/bug, lgtm, release/4.2, size/S

#1741 disable CVO and OLM for testing
  hack/deploy-logging.sh
  hack/test-logging.sh
Labels: approved, autoretest, kind/failing-test, lgtm, priority/critical-urgent, queue/blocks-others, release/4.2, size/M

#1744 Bug 1748751: Many `imfile: internal error? inotify provided watch de…
  rsyslog/vendored_src/rsyslog/rsyslog/plugins/imfile/imfile.c
Labels: approved, autoretest, bugzilla/valid-bug, component/rsyslog, kind/bug, lgtm, release/4.2, size/XS

#1745 Bug 1748769: Lots of `program '\/usr\/local\/bin\/undefined_field' e…
  rsyslog/undefined_field/undefined_field.go
Labels: approved, autoretest, bugzilla/valid-bug, component/rsyslog, kind/bug, lgtm, release/4.2, size/XS

#1746 Bug 1748769: Lots of `program '\/usr\/local\/bin\/undefined_field' e…
  rsyslog/undefined_field/undefined_field.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1749 Bug 1751339: Drop rsyslog support
  Makefile
Labels: approved, autoretest, bugzilla/valid-bug, component/rsyslog, kind/bug, lgtm, priority/critical-urgent, release/4.2, size/XS

#1753 bug 1752162: Drop rsyslog support from 4.1
  Makefile
Labels: approved, autoretest, bugzilla/valid-bug, cherry-pick-approved, component/rsyslog, kind/test-flake, lgtm, release/4.1, size/XS

#1754 Bug 1746377: Seed index patterns based on match to existing indices
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, backport/3.11, backport/4.1, bugzilla/valid-bug, lgtm, release/4.2, size/XS

#1755 Bug 1752850: Seed index patterns based on match to existing indices
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm, release/4.1, size/XS

#1757 curator/Dockerfile: allow latest python-elasticsearch
  curator/Dockerfile
Labels: approved, lgtm, size/XS

#1758 Bug 1753936: fluentd couldn't forward logs to rsyslog out:syslog: inv…
  fluentd/out_syslog.rb
  fluentd/out_syslog_buffered.rb
  hack/testing/entrypoint.sh
  hack/testing/templates/remote-syslog-listener-template.yaml
  test/remote-syslog.sh
Labels: approved, autoretest, backport/3.11, backport/4.1, bugzilla/valid-bug, component/fluentd, kind/bug, lgtm, release/4.3, size/XL
