Repository openshift/origin-aggregated-logging, pull requests merged in 2019-02, with the labels that each got.

#1511 Delete .0510-bz1656086-remove-index-patterns-with-bad-title.swp
  elasticsearch/init/.0510-bz1656086-remove-index-patterns-with-bad-title.swp
Labels: backport/3.11, lgtm

#1500 Add SearchGuard conf for Jaeger to ES image
  elasticsearch/init/0001-jaeger
  elasticsearch/sgconfig/sg_config.yml
  elasticsearch/sgconfig/sg_roles.yml
  elasticsearch/sgconfig/sg_roles_mapping.yml
Labels: lgtm, ok-to-test, size/M

#1503 fix race condition with oc exec
  hack/testing/check-EFK-running.sh
  hack/testing/entrypoint.sh
  hack/testing/templates/logging-ci-test-runner-template.yaml
  hack/testing/templates/test-template.yaml
  openshift/ci-operator/build-image/launch-e2e-test.sh
  openshift/ci-operator/build-image/setup-logging-for-e2e.sh
Labels: lgtm, size/M

#1504 add rsyslog image to logging
  hack/build-images.sh
  hack/templates/dev-builds.yaml
Labels: lgtm, size/M

#1516 must now use apiVersion: template.openshift.io/v1 for Templates
  hack/kopf/logging-es-kopf-template.yaml
  hack/templates/dev-builds.yaml
  hack/templates/pv-hostmount.yaml
  hack/templates/pv-nfs.yaml
  hack/testing/templates/fluentd_dc.yaml
  hack/testing/templates/logging-ci-test-runner-template.yaml
  hack/testing/templates/test-template.yaml
Labels: lgtm, size/S

#1521 use fewer resources than the default for es for ci machines
  openshift/ci-operator/build-image/setup-logging-for-e2e.sh
Labels: lgtm, size/XS

#1522 LOG-263. Document manual EventRouter deployment
  docs/deploy-event-router.md
  docs/release_notes.md
Labels: area/documentation, autoretest, kind/documentation, lgtm, retest-not-required-docs-only, size/L

#1528 revisions to support LOG-263
  docs/deploy-event-router.md
Labels: area/documentation, lgtm, retest-not-required-docs-only, size/S

#1525 Doc corrections
  README.md
  docs/access-control.md
  docs/mux-logging-service-diag1.dia
  docs/mux-logging-service-diag1.png
  docs/mux-logging-service-diag2.dia
  docs/mux-logging-service-diag2.png
  docs/mux-logging-service-diag3.dia
  docs/mux-logging-service-diag3.png
  docs/mux-logging-service-diag4.dia
  docs/mux-logging-service-diag4.png
  docs/mux-logging-service.md
  docs/quickstart.md
  docs/remote-syslog.md
  docs/troubleshooting-ci.md
Labels: area/documentation, autoretest, kind/documentation, lgtm, release/4.0, retest-not-required-docs-only, size/XL
