Repository openshift/origin-aggregated-logging, pull requests merged in 2020-09, with the labels that each got.

#1976 Fixed Fluentd unit tests on rhel8
  fluentd/lib/syslog_protocol/Gemfile
  test/unit/Dockerfile.rhel8
Labels: approved, bugzilla/valid-bug, lgtm

#1982 fix deploy-logging to always use CLO make deployment
  hack/deploy-logging.sh
  hack/testing/test-010-smoke-test-logging.sh
  hack/testing/util.sh
  openshift/ci-operator/build-image/cr.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1983 Fix elasticsearch6 rhel8 build
  elasticsearch/Dockerfile.rhel8
Labels: approved, bugzilla/valid-bug, lgtm

#1977 Bug 1868916: Move elasticsearch to OpenJDK 11
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/extra-jvm.options
  elasticsearch/install-es.sh
  elasticsearch/run.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1978 Bug 1852341: skip nil keys in json filter
  fluentd/lib/filter_parse_json_field/lib/filter_parse_json_field.rb
  fluentd/lib/filter_parse_json_field/test/filter_parse_json_field_test.rb
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1954 adding logic for restricting operator branches
  hack/deploy-logging.sh
Labels: approved, bugzilla/valid-bug, lgtm

#1962 LOG-814: creating kibana rh-manifest.txt file
  kibana/Dockerfile
  kibana/module_list.sh
  kibana/rh-manifest.txt
Labels: approved, bugzilla/valid-bug, lgtm

#1986 Bug 1872080: elasticsearch: fix prod plugin URLs
  elasticsearch/prep-install.prod
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1985 Workaround COPY behavior in OCP4
  elasticsearch/Dockerfile.rhel8
  elasticsearch/artifacts/README.MD
Labels: approved, bugzilla/valid-bug, lgtm

#1979 Replace logging-dump script with a warning to use must-gather
  hack/logging-dump.sh
Labels: approved, bugzilla/valid-bug, lgtm

#1989 Add review guidelines from source google doc
  README.md
  docs/REVIEW.md
Labels: approved, bugzilla/valid-bug, lgtm

#1988 Bug 1866490: Redirect user on 401 response
  kibana/Dockerfile
  kibana/Dockerfile.rhel8
  kibana/kibana.yml
  kibana/lib/openshift_logging_plugin/.eslintrc
  kibana/lib/openshift_logging_plugin/.gitignore
  kibana/lib/openshift_logging_plugin/README.md
  kibana/lib/openshift_logging_plugin/index.js
  kibana/lib/openshift_logging_plugin/package-lock.json
  kibana/lib/openshift_logging_plugin/package.json
  kibana/lib/openshift_logging_plugin/public/interceptors.js
  kibana/lib/origin-kibana-v5.6.16-1.zip
Labels: approved, bugzilla/valid-bug, lgtm

#1980 Bug 1873493: reenabling info and warning messages in kibana logs
  kibana/kibana.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
