Repository openshift/origin-aggregated-logging, pull requests merged in 2020-02, with the labels that each got.

#1820 Update images to6
  Makefile
  elasticsearch/sgconfig/roles.yml
  elasticsearch/sgconfig/roles_mapping.yml
  elasticsearch/utils/es_acl
  elasticsearch/utils/es_seed_acl
  hack/deploy-logging.sh
  hack/push-release.sh
  hack/templates/dev-builds.yaml
  test/cluster/functionality.sh
Labels: approved, size/L

#1818 rely on ES_PATH_CONF and remove obsolete tests and init scripts
  elasticsearch/init/0500-remove-index-patterns-without-uid
  elasticsearch/init/0510-bz1656086-remove-index-patterns-with-bad-title
  elasticsearch/init/0520-bz1658632-remove-old-sg-indices
  elasticsearch/init/0530-bz1667801-fix-kibana-replica-shards
  elasticsearch/probe/readiness.sh
  elasticsearch/utils/es_seed_acl
  elasticsearch/utils/es_util
  elasticsearch/utils/logging
  hack/testing/test-0500-remove-index-patterns-without-uid
  hack/testing/test-0530-bz1667801-fix-kibana-replica-shards
  test/0500-remove-index-patterns-without-uid
  test/0510-bz1656086-remove-index-patterns-with-bad-title
  test/0520-bz1658632-remove-old-sg-indices
  test/0530-bz1667801-fix-kibana-replica-shards
Labels: approved, es6x, release/4.4, size/XL

#1831 Bug 1794085: [fluentd] 3.11 remote syslog message is incomplete/truncated
  fluentd/generate_syslog_config.rb
  fluentd/out_syslog.rb
  fluentd/out_syslog_buffered.rb
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1828 enable smoke test for es6
  hack/deploy-logging.sh
  hack/test-e2e.sh
  hack/testing/common
  hack/testing/test-010-smoke-test-logging.sh
  openshift/ci-operator/build-image/cr.yaml
  openshift/ci-operator/build-image/setup-logging-for-e2e.sh
Labels: approved, es6x, lgtm, release/4.5, size/L

#1829 Increase timeout for waiting for port forwarding
  hack/build-images.sh
Labels: approved, lgtm, size/XS

#1833 Make target kickoff
  Makefile
Labels: approved, lgtm, size/S

#1832 Drop xtrace verbosity from deploy and test scripts
  hack/build-images.sh
  hack/deploy-logging.sh
  hack/enable-kibana-msearch-access.sh
  hack/get-machine-run-tests.sh
  hack/logging-dump.sh
  hack/testing/test-010-smoke-test-logging.sh
  hack/vendor-kibana-lib.sh
  hack/vendor/olm-test-script/e2e-olm.sh
  test/0540-bz1710868-fix-access-to-root-endpoint
  test/json-parsing.sh
  test/kibana_dashboards.sh
  test/utf8-characters.sh
  test/viaq-data-model.sh
Labels: approved, lgtm, size/M

#1797 LOG-569: Static index config
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/Gemfile
  fluentd/lib/fluent-plugin-viaq_data_model/.travis.yml
  fluentd/lib/fluent-plugin-viaq_data_model/Gemfile
  fluentd/lib/fluent-plugin-viaq_data_model/LICENSE
  fluentd/lib/fluent-plugin-viaq_data_model/README.md
  fluentd/lib/fluent-plugin-viaq_data_model/Rakefile
  fluentd/lib/fluent-plugin-viaq_data_model/Vagrantfile
  fluentd/lib/fluent-plugin-viaq_data_model/filter-viaq_data_model.conf
  fluentd/lib/fluent-plugin-viaq_data_model/fluent-plugin-viaq_data_model.gemspec
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model_systemd.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
Labels: approved, component/fluentd, es6x, lgtm, release/4.4, size/M
