Repository openshift/origin-aggregated-logging, pull requests merged in 2020-04, with the labels that each got.

#1855 Fixed ES access via es-proxy
  elasticsearch/sgconfig/config.yml
  elasticsearch/sgconfig/roles.yml
  hack/testing/util.sh
  test/multi_tenancy.sh
Labels: approved, lgtm

#1867 add component to OWNER
  OWNERS
Labels: approved, lgtm, release/4.5

#1869 [kibana] Fix config options override per env variable
  kibana/utils
Labels: approved, lgtm

#1861 Bug 1810182: Make images buildable by buildah
  Makefile
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/elasticsearch.repo
  fluentd/Dockerfile.centos7
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/kibana.repo
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.4

#1874 Support syslog rfc5424
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/lib/fluent/plugin/out_remote_syslog.rb
  fluentd/vendored_gem_src/remote_syslog_sender/lib/remote_syslog_sender/sender.rb
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol/packet.rb
Labels: approved, lgtm

#1873 Define Dockerfile env var values once
  fluentd/Dockerfile
Labels: approved, lgtm

#1876 Bug 1810220: Modify Dockerfile to mitigate issue with buildah
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  kibana/Dockerfile
  kibana/Dockerfile.centos7
Labels: approved, bugzilla/valid-bug, lgtm, release/3.11

#1879 Bug 1826096: Fixing failing image tests
  fluentd/Dockerfile.centos7
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/run.sh
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#1880 Bug 1825275: Modify Dockerfile to mitigate issue with buildah
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  kibana/Dockerfile
  kibana/Dockerfile.centos7
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1877 Bug 1822686: Require python2-pip in vendoring and removing python-thrift
  curator/Dockerfile
  curator/Dockerfile.centos7
Labels: approved, backport/4.4, bugzilla/low, bugzilla/valid-bug, lgtm, release/4.5

#1886 Bug 1822686: Update to python3 and remove python-thrift dependency from python-elasticsearch
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/lib/oalconverter/convert.py
  curator/lib/oalconverter/util.py
  curator/rh-manifest.txt
  curator/vendor/futures-3.3.0.tar.gz
  curator/vendor/ruamel.yaml-0.16.10.tar.gz
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, release/4.5

#1878 Bug 1821998: Use kubernetes.container_name.raw field
  elasticsearch/kibana_ui_objects/k8s-dashboard.json
  elasticsearch/kibana_ui_objects/k8s-search.json
  elasticsearch/kibana_ui_objects/k8s-visualizations.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1888 Bug 1822686: Dockerfile should install python3 first
  curator/Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
