Repository openshift/origin-aggregated-logging, pull requests merged in 2020-10, with the labels that each got.

#1994 Bug 1882232: Enable admin_reader to monitor cluster
  elasticsearch/sgconfig/roles.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1993 Bug 1883079: Treat empty string as nil in fluentd-plugin-kafka#read_ssl_file
  fluentd/fluent-plugin-kafka.source0001.patch
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1991 Bug 1884812: Addressing permissions warning in ES start up logs
  elasticsearch/install-es.sh
  elasticsearch/run.sh
  elasticsearch/utils/logging
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1998 Bug 1885481: Rely on Koji artifacts
  elasticsearch/Dockerfile
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, release/4.2

#2000 Bug 1885481: Fix dep version in Dockerfile
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, needs-rebase

#1995 Bug 1881996: skip nil keys in json filter
  fluentd/lib/filter_parse_json_field/lib/filter_parse_json_field.rb
  fluentd/lib/filter_parse_json_field/test/filter_parse_json_field_test.rb
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1992 Bug 1883673: Redirect user on auth failure
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/kibana.yml
  kibana/lib/openshift_logging_plugin/.eslintrc
  kibana/lib/openshift_logging_plugin/.gitignore
  kibana/lib/openshift_logging_plugin/README.md
  kibana/lib/openshift_logging_plugin/index.js
  kibana/lib/openshift_logging_plugin/package-lock.json
  kibana/lib/openshift_logging_plugin/package.json
  kibana/lib/openshift_logging_plugin/public/interceptors.js
  kibana/lib/origin-kibana-v5.6.16-1.zip
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2008 [release-4.2] Bug 1885481: Fix more deps in Dockerfile
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2012 fix fluent unit test image
  test/unit/Dockerfile
  test/unit/Dockerfile.rhel8
  test/unit/run.sh
Labels: approved, lgtm

#2004 Add GH pull request template
  .github/pull_request_template.md
Labels: approved, lgtm

#2003 GitHub bug issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm

#2016 Add USER 0 to test/unit/Dockerfile to fix CI
  test/unit/Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#2002 LOG-867: Creating es rh-manifest.txt file and script to recreate it
  elasticsearch/Dockerfile.origin
  elasticsearch/lib/tattletale/module_list.sh
  elasticsearch/lib/tattletale/tattletale-1.2.0.Beta2.zip
  elasticsearch/rh-manifest.txt
  kibana/module_list.sh
Labels: approved, lgtm

#2019 fix smoke test to use correct operator branches
  Makefile
  hack/deploy-logging.sh
  test/unit/Dockerfile
  test/unit/Dockerfile.rhel8
  test/unit/run.sh
Labels: approved

#2006 Bug 1889385: Update openshift-elasticsearch-plugin to close clients
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
