Repository openshift/origin-aggregated-logging, pull requests merged in 2020-06, with the labels that each got.

#1910 Bug 1842721: vendor ruamel.yaml
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/requirements.txt
  curator/run.sh
  curator/vendor/boto3-1.13.18-py2.py3-none-any.whl
  curator/vendor/boto3-1.13.20-py2.py3-none-any.whl
  curator/vendor/ruamel.yaml-0.15.100.tar.gz
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1897 Bug 1840274: Add script to let fluentd check ES version
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/wait_for_es_version.rb
  fluentd/wait_for_es_version.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1909 Bug 1842517: Rely on koji to get maven dependencies
  elasticsearch/Dockerfile
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.4

#1904 Bug 1833486: Mapping "template" field becomes "index_patterns"
  elasticsearch/index_templates/com.redhat.viaq-openshift-orphaned.template.json
  elasticsearch/index_templates/common.settings.kibana.template.json
  elasticsearch/index_templates/common.settings.operations.orphaned.json
  elasticsearch/index_templates/common.settings.operations.template.json
  elasticsearch/index_templates/common.settings.project.template.json
  elasticsearch/index_templates/jaeger-service.json
  elasticsearch/index_templates/jaeger-span.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1911 Bug 1842439: Vendor ruamel.yaml
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/requirements.txt
  curator/run.sh
  curator/vendor/boto3-1.13.18-py2.py3-none-any.whl
  curator/vendor/boto3-1.13.20-py2.py3-none-any.whl
  curator/vendor/ruamel.yaml-0.15.100.tar.gz
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#1916 Bug 1838153: Fix index patterns in index templates
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1912 Bug 1842357: Limit role project_user to access only owned kibana idx
  elasticsearch/sgconfig/roles.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1921 Bug 1844097: Removing check that keeps only elected master seeding
  elasticsearch/init.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1923 Bug 1845517: limit ffi version
  fluentd/Dockerfile.centos7
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#1882 Fluent plugins to support rfc5424 params
  Makefile
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/Gemfile
  fluentd/lib/filter_parse_json_field/lib/filter_parse_json_field.rb
  fluentd/lib/filter_parse_json_field/test/filter_parse_json_field_test.rb
  fluentd/lib/fluent-plugin-remote_syslog/.travis.yml
  fluentd/lib/fluent-plugin-remote_syslog/CHANGELOG.md
  fluentd/lib/fluent-plugin-remote_syslog/Gemfile
  fluentd/lib/fluent-plugin-remote_syslog/Gemfile.lock
  fluentd/lib/fluent-plugin-remote_syslog/LICENSE.txt
  fluentd/lib/fluent-plugin-remote_syslog/README.md
  fluentd/lib/fluent-plugin-remote_syslog/Rakefile
  fluentd/lib/fluent-plugin-remote_syslog/VERSION
  fluentd/lib/fluent-plugin-remote_syslog/fluent-plugin-remote_syslog.gemspec
  fluentd/lib/fluent-plugin-remote_syslog/lib/fluent/plugin/out_remote_syslog.rb
  fluentd/lib/fluent-plugin-remote_syslog/test/plugin/out_remote_syslog.rb
  fluentd/lib/fluent-plugin-remote_syslog/test/test_helper.rb
  fluentd/lib/remote_syslog_sender/Gemfile
  fluentd/lib/remote_syslog_sender/Gemfile.lock
  fluentd/lib/remote_syslog_sender/LICENSE
  fluentd/lib/remote_syslog_sender/README.md
  fluentd/lib/remote_syslog_sender/Rakefile
  fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender.rb
  fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/sender.rb
  fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/tcp_sender.rb
  fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/udp_sender.rb
  fluentd/lib/remote_syslog_sender/remote_syslog_sender.gemspec
  fluentd/lib/remote_syslog_sender/test/helper.rb
  fluentd/lib/remote_syslog_sender/test/test_remote_syslog_logger.rb
  fluentd/lib/syslog_protocol/Gemfile
  fluentd/lib/syslog_protocol/Gemfile.lock
  fluentd/lib/syslog_protocol/README.md
  fluentd/lib/syslog_protocol/Rakefile
  fluentd/lib/syslog_protocol/lib/syslog_protocol.rb
  fluentd/lib/syslog_protocol/lib/syslog_protocol/common.rb
  fluentd/lib/syslog_protocol/lib/syslog_protocol/logger.rb
  fluentd/lib/syslog_protocol/lib/syslog_protocol/packet.rb
  fluentd/lib/syslog_protocol/lib/syslog_protocol/parser.rb
  fluentd/lib/syslog_protocol/syslog_protocol.gemspec
  fluentd/lib/syslog_protocol/test/helper.rb
  fluentd/lib/syslog_protocol/test/test_logger.rb
  fluentd/lib/syslog_protocol/test/test_packet.rb
  fluentd/lib/syslog_protocol/test/test_parser.rb
  fluentd/vendored_gem_src/remote_syslog_sender/Gemfile
Labels: approved, lgtm

#1924 Bug 1846126: Rely on koji to get maven dependencies
  elasticsearch/Dockerfile
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1928 Bug 1840274: Enable ruby from scl if exists
  fluentd/wait_for_es_version.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
