Repository openshift/origin-aggregated-logging, pull requests merged in 2020-11, with the labels that each got.

#1843 Minor fix to print the reason for CSV creation not Succeeding.
  hack/vendor/olm-test-script/e2e-olm.sh
Labels: approved, lgtm, lifecycle/stale, release-4.7, size/XS

#2013 Fix Makefile targets to build individual components
  Makefile
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.origin
  hack/build-component-image.sh
  hack/deploy-component-image.sh
  kibana/Dockerfile
  kibana/Dockerfile.rhel8
Labels: approved, lgtm

#1967 Bug 1877906: remove unwanted flag "--setopt=tsflags=nodocs"
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  fluentd/Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test, release-4.7

#2020 [release-3.11] Bug 1889385: Fetch the artifact that is used later
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2021 Add indices:admin/mappings/get permission to READ group
  elasticsearch/sgconfig/action_groups.yml
  elasticsearch/sgconfig/roles.yml
Labels: approved, lgtm
