Repository openshift/origin-aggregated-logging, pull requests merged in 2020-03, with the labels that each got.

#1844 Modify Elasticsearch Dockerfile to mitigate issue with buildah
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, lgtm, release/4.5, size/XS

#1827 elasticsearch/sgconfig: Added a role with DLS query to support multit…
  elasticsearch/sgconfig/roles.yml
  elasticsearch/sgconfig/roles_mapping.yml
  elasticsearch/utils/aliases
  hack/deploy-logging.sh
  hack/test-e2e.sh
  hack/testing/util.sh
  openshift/ci-operator/build-image/Dockerfile
  test/multi_tenancy.sh
Labels: approved, feature/es6, lgtm, release/4.5, size/L

#1854 Update OWNERS
  OWNERS
Labels: approved, lgtm

#1858 [fluentd] Pin gem versions
  fluentd/Gemfile
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/activemodel/activemodel.gemspec
  fluentd/vendored_gem_src/activemodel/lib/active_model/gem_version.rb
  fluentd/vendored_gem_src/activesupport/activesupport.gemspec
  fluentd/vendored_gem_src/activesupport/lib/active_support/gem_version.rb
  fluentd/vendored_gem_src/excon/lib/excon/error.rb
  fluentd/vendored_gem_src/excon/lib/excon/ssl_socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/version.rb
  fluentd/vendored_gem_src/http-form_data/CHANGES.md
  fluentd/vendored_gem_src/http-form_data/lib/http/form_data.rb
  fluentd/vendored_gem_src/http-form_data/lib/http/form_data/urlencoded.rb
  fluentd/vendored_gem_src/http-form_data/lib/http/form_data/version.rb
  fluentd/vendored_gem_src/http-form_data/spec/lib/http/form_data/urlencoded_spec.rb
  fluentd/vendored_gem_src/recursive-open-struct/.travis.yml
  fluentd/vendored_gem_src/recursive-open-struct/AUTHORS.txt
  fluentd/vendored_gem_src/recursive-open-struct/CHANGELOG.md
  fluentd/vendored_gem_src/recursive-open-struct/CONTRIBUTING.md
  fluentd/vendored_gem_src/recursive-open-struct/README.md
  fluentd/vendored_gem_src/recursive-open-struct/lib/recursive_open_struct.rb
  fluentd/vendored_gem_src/recursive-open-struct/lib/recursive_open_struct/version.rb
  fluentd/vendored_gem_src/recursive-open-struct/recursive-open-struct.gemspec
  hack/update-fluentd-vendor-gems.sh
Labels: approved, lgtm

#1859 remove unused cert domain. fix operators ability to fetch templates
  elasticsearch/sgconfig/roles.yml
Labels: approved, lgtm, release/4.5

#1860 Added fluent-plugin-remote_syslog plugin gem
  fluentd/Gemfile
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/.travis.yml
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/CHANGELOG.md
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/Gemfile
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/LICENSE.txt
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/README.md
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/Rakefile
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/VERSION
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/fluent-plugin-remote_syslog.gemspec
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/lib/fluent/plugin/out_remote_syslog.rb
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/test/plugin/out_remote_syslog.rb
  fluentd/vendored_gem_src/fluent-plugin-remote_syslog/test/test_helper.rb
  fluentd/vendored_gem_src/remote_syslog_sender/Gemfile
  fluentd/vendored_gem_src/remote_syslog_sender/LICENSE
  fluentd/vendored_gem_src/remote_syslog_sender/README.md
  fluentd/vendored_gem_src/remote_syslog_sender/Rakefile
  fluentd/vendored_gem_src/remote_syslog_sender/lib/remote_syslog_sender.rb
  fluentd/vendored_gem_src/remote_syslog_sender/lib/remote_syslog_sender/sender.rb
  fluentd/vendored_gem_src/remote_syslog_sender/lib/remote_syslog_sender/tcp_sender.rb
  fluentd/vendored_gem_src/remote_syslog_sender/lib/remote_syslog_sender/udp_sender.rb
  fluentd/vendored_gem_src/remote_syslog_sender/remote_syslog_sender.gemspec
  fluentd/vendored_gem_src/remote_syslog_sender/test/helper.rb
  fluentd/vendored_gem_src/remote_syslog_sender/test/test_remote_syslog_logger.rb
Labels: approved, lgtm, release/4.5

#1862 [fluentd] Fix Dockerfile.centos7 builds
  fluentd/Dockerfile.centos7
Labels: approved, lgtm

#1863 Add role for indexmanagement
  elasticsearch/sgconfig/roles_mapping.yml
Labels: approved, feature/es6, lgtm, release/4.5
