Repository openshift/origin-aggregated-logging, pull requests merged in 2020-05, with the labels that each got.

#1885 Bug 1821670: Make images buildah compatible
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/elasticsearch.repo
  kibana/Dockerfile
  kibana/Dockerfile.centos7
  kibana/kibana.repo
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.3

#1890 Bug 1809498: Limit shards for security index to fix upgrade to 4.5
  elasticsearch/utils/es_seed_acl
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1891 Migrate image building and publish to use podman
  hack/build-images.sh
Labels: approved, bugzilla/valid-bug, lgtm

#1896 Bug 1836230: Remove fluent centos dependency
  fluentd/Dockerfile.centos7
  hack/testing/test-010-smoke-test-logging.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1895 Bug 1836217: Remove fluent centos dependency
  fluentd/Dockerfile.centos7
  hack/deploy-logging.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1893 Bug 1836450: Restricting which es node can seed -- limiting to just elected master
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/init.sh
  elasticsearch/init/0010-seed-acl
  elasticsearch/probe/readiness.sh
  elasticsearch/utils/logging
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1901 Bug 1839326: Install python-six first and verify curator is installed upon build
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/vendor/01_six-1.14.0.tar.gz
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1899 Bug 1838929: Remove module/ingest-geoip
  elasticsearch/install.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1902 Bug 1837867: Partial fix. Remove dsl restriction for admin_user
  elasticsearch/sgconfig/roles.yml
  elasticsearch/sgconfig/roles_mapping.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1903 Adding Makefile targets for building and deploying each component
  Makefile
  hack/build-component-image.sh
  hack/deploy-component-image.sh
Labels: approved, bugzilla/valid-bug, lgtm

#1907 Bug 1841892: Use koji to fetch rcm artifacts
  elasticsearch/Dockerfile
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
