Repository openshift/origin-aggregated-logging, pull requests merged in 2020-07, with the labels that each got.

#1932 Added missing newline at end of readiness.sh
  elasticsearch/probe/readiness.sh
Labels: approved, lgtm

#1931 Cleanup centos7 references
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/install-centos7-deps.sh
  elasticsearch/Dockerfile.centos7
  fluentd/Dockerfile.centos7
  kibana/Dockerfile.centos7
  test/Dockerfile.centos7
Labels: approved, lgtm

#1936 Bug 1835396: Disable http/2 for kubernetes-client
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1938 fix update-fluentd-vendor-gems.sh and rely on Gemfile.lock
  fluentd/Gemfile
  fluentd/source.jemalloc
  hack/update-fluentd-vendor-gems.sh
Labels: approved, lgtm

#1941 Bug 1850849: disable kibana metrics to address CVEs
  kibana/kibana.yml
Labels: approved, lgtm

#1945 Bug 1846126: Revert the elasticsearch-prometheus-exporter version
  elasticsearch/Dockerfile
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1946 expanding on hack/logging-dump.sh to also include CRs and CSVs
  hack/logging-dump.sh
Labels: approved, lgtm

#1948 Bug 1795897: curator: base on py36
  curator/Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1949 Bug 1795897: curator/Dockerfile: don't be picky about where pip installs curator
  curator/Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1951 fixing smoke test for release-4.5
  hack/deploy-logging.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1947 Prepare for RHEL 8
  elasticsearch/Dockerfile.rhel8
  elasticsearch/utils/es_util_env
  kibana/Dockerfile.rhel8
Labels: approved, lgtm
