Repository openshift/origin-aggregated-logging, pull requests merged in 2020-08, with the labels that each got.

#1958 Bug 1860793: Vendor ruamel.yaml
  curator/Dockerfile
  curator/Dockerfile.centos7
  curator/requirements.txt
  curator/run.sh
  curator/vendor/boto3-1.13.18-py2.py3-none-any.whl
  curator/vendor/boto3-1.13.20-py2.py3-none-any.whl
  curator/vendor/ruamel.yaml-0.15.100.tar.gz
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, do-not-merge/hold, lgtm

#1959 Bug 1865777: Update readiness probe to handle stderr and connect log
  elasticsearch/utils/logging
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1961 removing jq from ES images
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/utils/logging
  hack/build-component-image.sh
Labels: approved, lgtm

#1960 Bug 1671226: Remove obsolete Kibana utilites from image
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/README.md
  elasticsearch/install.sh
  elasticsearch/kibana_ui_objects/k8s-dashboard.json
  elasticsearch/utils/es_load_kibana_ui_objects
  elasticsearch/utils/export-kibana-objects
  hack/testing/test-kibana-dashboards.sh
  test/kibana_dashboards.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1966 Bug 1868416: downstream elasticsearch version marked as SNAPSHOT
  elasticsearch/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1969 Bug 1832783: X-Frame-Option not set by default
  kibana/kibana.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1970 Bug 1870650: removed duplicate syslog_protocol gem from vendored_gem_src
  fluentd/vendored_gem_src/syslog_protocol/Gemfile
  fluentd/vendored_gem_src/syslog_protocol/README.md
  fluentd/vendored_gem_src/syslog_protocol/Rakefile
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol.rb
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol/common.rb
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol/logger.rb
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol/packet.rb
  fluentd/vendored_gem_src/syslog_protocol/lib/syslog_protocol/parser.rb
  fluentd/vendored_gem_src/syslog_protocol/syslog_protocol.gemspec
  fluentd/vendored_gem_src/syslog_protocol/test/helper.rb
  fluentd/vendored_gem_src/syslog_protocol/test/test_logger.rb
  fluentd/vendored_gem_src/syslog_protocol/test/test_packet.rb
  fluentd/vendored_gem_src/syslog_protocol/test/test_parser.rb
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
