Repository openshift/origin-aggregated-logging, pull requests merged in 2020-01, with the labels that each got.

#1814 LOG-608: Pull in opendistro_security v0.10.1.0
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
Labels: approved, es6x, lgtm, size/XS

#1331 [3.10] More readable format for curator logs
  curator/src/util.py
Labels: lgtm, release/3.10, size/XS

#1815 update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#1807 Upgrade model to 2020.01.23.0
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: approved, es6x, lgtm, size/M
