Repository openshift/origin-aggregated-logging, pull requests merged in 2021-04, with the labels that each got.

#2067 Bug 1881445: Fixed 'time' type to be Fluent::EventTime
  fluentd/lib/parser_viaq_host_audit/lib/parser_viaq_host_audit.rb
  fluentd/lib/parser_viaq_host_audit/test/parser_viaq_host_audit_test.rb
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2097 Bug 1940563: Rebuild elasticsearch to bump the version jackson dependency to v2.10.5
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/install-es.sh
  elasticsearch/rh-manifest.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2098 [release-5.0] mainline fixes
  Makefile
  curator/Dockerfile
  elasticsearch/Dockerfile.rhel8
  fluentd/Dockerfile
  hack/build-images.sh
  hack/deploy-logging.sh
  kibana/Dockerfile.rhel8
  test/eventrouter.sh
  test/unit/Dockerfile.rhel8
Labels: approved, lgtm

#2096 updating es security manifest
  elasticsearch/rh-manifest.txt
Labels: approved, lgtm

#2086 LOG-660: Added fluent-plugin-label-router to support Forwarder Label Selector
  fluentd/Gemfile
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/fluent-plugin-label-router/Gemfile
  fluentd/vendored_gem_src/fluent-plugin-label-router/LICENSE
  fluentd/vendored_gem_src/fluent-plugin-label-router/README.md
  fluentd/vendored_gem_src/fluent-plugin-label-router/Rakefile
  fluentd/vendored_gem_src/fluent-plugin-label-router/fluent-plugin-label-router.gemspec
  fluentd/vendored_gem_src/fluent-plugin-label-router/lib/fluent/plugin/out_label_router.rb
  fluentd/vendored_gem_src/fluent-plugin-label-router/test/helper.rb
  fluentd/vendored_gem_src/fluent-plugin-label-router/test/plugin/test_out_label_router.rb
Labels: approved, lgtm

#2077 Converting JKS format to PKCS for elasticsearch
  elasticsearch/run.sh
  elasticsearch/utils/es_seed_acl
  elasticsearch/utils/logging
  hack/ssl/createSecrets.sh
  hack/ssl/etc/root-ca.conf
  hack/ssl/etc/signing-ca.conf
  hack/ssl/gen_root_ca.sh
  hack/ssl/generateExampleKeys.sh
  hack/ssl/generateJKSChain.sh
  hack/ssl/generatePEMCerts.sh
Labels: approved, lgtm

#2099 Bug 1940563: Fix Dockerfile to be buildable by ART
  .gitignore
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/ci-env.sh
  elasticsearch/dummy.zip
  elasticsearch/install-es.sh
  elasticsearch/install.sh
  elasticsearch/prep-install.origin
  elasticsearch/prep-install.prod
  elasticsearch/sources
  hack/build-component-image.sh
  hack/build-images.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2111 Update owners file to label PR on Dockerfile changes
  OWNERS
Labels: approved, lgtm

#2113 LOG-1272: Fix source of elasticsearch-prometheus-exporter
  elasticsearch/Dockerfile.rhel8
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/sources
Labels: approved, lgtm

#2106 Bug 1933978: Update OD security dependency to resolve kibana index migration issue
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.6

#2110 LOG-1279: Add placeholder for linting tasks
  Makefile
  hack/run-linter
Labels: approved, lgtm, release/5.1

#2115 removed earlier prometheus exporter nvr
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, lgtm

#2108 Remove obsolete files from the fluentd image
  fluentd/Dockerfile
  fluentd/configs.d/filter-parse-json-field.conf
  fluentd/configs.d/filter-post-z-retag-one.conf
  fluentd/configs.d/filter-post-z-retag-two.conf
  fluentd/configs.d/input-pre-debug.conf
  fluentd/configs.d/input-pre-monitor.conf
  fluentd/configs.d/openshift/README
  fluentd/configs.d/openshift/filter-exclude-journal-debug.conf
  fluentd/configs.d/openshift/filter-k8s-meta.conf
  fluentd/configs.d/openshift/filter-k8s-record-transform.conf
  fluentd/configs.d/openshift/filter-kibana-transform.conf
  fluentd/configs.d/openshift/filter-post-genid.conf
  fluentd/configs.d/openshift/filter-pre-force-utf8.conf
  fluentd/configs.d/openshift/filter-retag-journal.conf
  fluentd/configs.d/openshift/filter-syslog-record-transform.conf
  fluentd/configs.d/openshift/filter-viaq-data-model.conf
  fluentd/configs.d/openshift/input-pre-prometheus-metrics.conf
  fluentd/configs.d/openshift/input-pre-systemd.conf
  fluentd/configs.d/openshift/output-applications.conf
  fluentd/configs.d/openshift/output-es-config.conf
  fluentd/configs.d/openshift/output-es-ops-config.conf
  fluentd/configs.d/openshift/output-es-ops-retry.conf
  fluentd/configs.d/openshift/output-es-retry.conf
  fluentd/configs.d/openshift/output-operations.conf
  fluentd/configs.d/openshift/system.conf
  fluentd/configs.d/user/fluent.conf
  fluentd/configs.d/user/secure-forward.conf
  fluentd/configs.d/user/throttle-conf.yaml
  fluentd/lib/generate_throttle_configs/Gemfile
  fluentd/lib/generate_throttle_configs/Rakefile
  fluentd/lib/generate_throttle_configs/generate_throttle_configs.gemspec
  fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb
  fluentd/lib/generate_throttle_configs/test/generate_throttle_configs_test.rb
  fluentd/lib/generate_throttle_configs/test/test_helper.rb
  fluentd/run.sh
Labels: approved, lgtm

#2116 LOG-1131: Updating order for kibana index template
  elasticsearch/index_templates/common.settings.kibana.template.json
Labels: approved, lgtm
