Repository openshift/origin-aggregated-logging, pull requests merged in 2021-07, with the labels that each got.

#2147 fix storage class to match GCP
  openshift/ci-operator/build-image/cr.yaml
Labels: approved, lgtm

#2146 LOG-1499: Vendor fluent-plugin-elasticsearch v5.0.5 to drop messages
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/excon/README.md
  fluentd/vendored_gem_src/excon/data/cacert.pem
  fluentd/vendored_gem_src/excon/excon.gemspec
  fluentd/vendored_gem_src/excon/lib/excon.rb
  fluentd/vendored_gem_src/excon/lib/excon/connection.rb
  fluentd/vendored_gem_src/excon/lib/excon/constants.rb
  fluentd/vendored_gem_src/excon/lib/excon/headers.rb
  fluentd/vendored_gem_src/excon/lib/excon/instrumentors/logging_instrumentor.rb
  fluentd/vendored_gem_src/excon/lib/excon/instrumentors/standard_instrumentor.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/capture_cookies.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/decompress.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/expects.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/mock.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/redirect_follower.rb
  fluentd/vendored_gem_src/excon/lib/excon/response.rb
  fluentd/vendored_gem_src/excon/lib/excon/socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/ssl_socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/test/plugin/server/exec.rb
  fluentd/vendored_gem_src/excon/lib/excon/test/server.rb
  fluentd/vendored_gem_src/excon/lib/excon/unix_socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/utils.rb
  fluentd/vendored_gem_src/excon/lib/excon/version.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/ISSUE_TEMPLATE/bug_report.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/ISSUE_TEMPLATE/feature_request.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/issue-auto-closer.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/linux.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/macos.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/windows.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.travis.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/History.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.ElasticsearchGenID.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.ElasticsearchInput.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.Troubleshooting.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/fluent-plugin-elasticsearch.gemspec
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/gemfiles/Gemfile.without.ilm
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_error_handler.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch_data_stream.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_error_handler.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_fallback_selector.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_index_lifecycle_management.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_tls.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_in_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_index_alias_template.json
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_index_template.json
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch_data_stream.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch_dynamic.rb
Labels: approved, lgtm

#2118 LOG-1213: New plugin metric for inbound log data loss at the collector jira ticket log 1032
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  fluentd/lib/fluent-plugin-collected/Gemfile
  fluentd/lib/fluent-plugin-collected/LICENSE
  fluentd/lib/fluent-plugin-collected/README.md
  fluentd/lib/fluent-plugin-collected/Rakefile
  fluentd/lib/fluent-plugin-collected/fluent-plugin-collected.gemspec
  fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb
  fluentd/lib/fluent-plugin-collected/test/plugin/test_in_collected_tail_monitor.rb
  fluentd/lib/fluent-plugin-collected/test/test_helper.rb
  hack/build-component-image.sh
Labels: approved, lgtm, midstream/Dockerfile

#2126 BZ-1897642: Decrease number of gc.log files managed by -Xlog option
  elasticsearch/run.sh
Labels: approved, lgtm

#2153 Update OWNERS
  OWNERS
Labels: approved, lgtm

#2150 LOG-1560: Update OD security dependency to resolve kibana index migra…
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, lgtm

#2151 LOG-1559: Update OD security dependency to resolve kibana index migra…
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, lgtm, midstream/Dockerfile

#2133 LOG-1379: Updated viaq data model
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/common.settings.operations.template.json
  elasticsearch/index_templates/common.settings.project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
  elasticsearch/init/0200-seed-index-templates
  hack/update-viaq-data-model.sh
Labels: approved, lgtm

#2155 LOG-1569: Vendor fluent-plugin-elasticsearch v5.0.5 to drop messages
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/excon/README.md
  fluentd/vendored_gem_src/excon/data/cacert.pem
  fluentd/vendored_gem_src/excon/excon.gemspec
  fluentd/vendored_gem_src/excon/lib/excon.rb
  fluentd/vendored_gem_src/excon/lib/excon/connection.rb
  fluentd/vendored_gem_src/excon/lib/excon/constants.rb
  fluentd/vendored_gem_src/excon/lib/excon/headers.rb
  fluentd/vendored_gem_src/excon/lib/excon/instrumentors/logging_instrumentor.rb
  fluentd/vendored_gem_src/excon/lib/excon/instrumentors/standard_instrumentor.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/capture_cookies.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/decompress.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/expects.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/mock.rb
  fluentd/vendored_gem_src/excon/lib/excon/middlewares/redirect_follower.rb
  fluentd/vendored_gem_src/excon/lib/excon/response.rb
  fluentd/vendored_gem_src/excon/lib/excon/socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/ssl_socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/test/plugin/server/exec.rb
  fluentd/vendored_gem_src/excon/lib/excon/test/server.rb
  fluentd/vendored_gem_src/excon/lib/excon/unix_socket.rb
  fluentd/vendored_gem_src/excon/lib/excon/utils.rb
  fluentd/vendored_gem_src/excon/lib/excon/version.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/ISSUE_TEMPLATE/bug_report.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/ISSUE_TEMPLATE/feature_request.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/issue-auto-closer.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/linux.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/macos.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.github/workflows/windows.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/.travis.yml
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/History.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.ElasticsearchGenID.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.ElasticsearchInput.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.Troubleshooting.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/README.md
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/fluent-plugin-elasticsearch.gemspec
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/gemfiles/Gemfile.without.ilm
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_error_handler.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch_data_stream.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_error_handler.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_fallback_selector.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_index_lifecycle_management.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_elasticsearch_tls.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_in_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_index_alias_template.json
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_index_template.json
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch_data_stream.rb
  fluentd/vendored_gem_src/fluent-plugin-elasticsearch/test/plugin/test_out_elasticsearch_dynamic.rb
  fluentd/vendored_gem_src/oj/oj.gemspec
Labels: approved, lgtm, release/5.1

#2157 Ingest plugin install path
  elasticsearch/ci-env.sh
Labels: approved, lgtm
