Repository openshift/origin-aggregated-logging, pull requests merged in 2021-09, with the labels that each got.

#2171 Fix multitenancy check of project users to infra indices
  hack/testing/util.sh
  test/multi_tenancy.sh
Labels: lgtm, approved

#2174 Use pinned operand image versions from quay.io
  Makefile
  hack/deploy-logging.sh
Labels: lgtm, approved

#2170 Fixed upstream component versions
  curator/Dockerfile
  curator/Dockerfile.in
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  kibana/Dockerfile
  kibana/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile

#2176 In fluentd-plugin-cloudwatch-logs, added support for passing the ssl_verify_peer flag to the AWS SDK
  fluentd/fluent-plugin-cloudwatch-logs.source0001.patch
Labels: lgtm, approved

#2180 Sync dockefiles with midstream
  curator/Dockerfile
  curator/Dockerfile.in
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  kibana/Dockerfile
  kibana/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile

#2175 LOG-1494: Added Formatter single_json_value
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  fluentd/lib/formatter-single-json-value/Gemfile
  fluentd/lib/formatter-single-json-value/LICENSE.txt
  fluentd/lib/formatter-single-json-value/README.md
  fluentd/lib/formatter-single-json-value/Rakefile
  fluentd/lib/formatter-single-json-value/formatter-single-json-value.gemspec
  fluentd/lib/formatter-single-json-value/lib/formatter_single_json_value.rb
  fluentd/lib/formatter-single-json-value/test/formatter_single_json_value_test.rb
  fluentd/lib/formatter-single-json-value/test/test_helper.rb
Labels: lgtm, approved, midstream/Dockerfile

#2177 Bug 2002671: Improve logging-dump.sh (backport of LOG-1733 to 3.11)
  hack/README-dump.md
  hack/logging-dump.sh
Labels: do-not-merge/hold, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#2183 Fix license labels to Apache-2.0
  curator/Dockerfile
  curator/Dockerfile.in
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  kibana/Dockerfile
  kibana/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile

#2185 LOG-1337: Fix deployment check for collector named 'collector'
  hack/deploy-logging.sh
Labels: lgtm, approved, release/5.3

#2184 Sync dockerfiles with midstream
  curator/Dockerfile
  curator/Dockerfile.in
  curator/origin-meta.yaml
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/origin-meta.yaml
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  fluentd/origin-meta.yaml
  hack/build-component-image.sh
  kibana/Dockerfile
  kibana/Dockerfile.in
  kibana/origin-meta.yaml
Labels: lgtm, approved, midstream/Dockerfile

#2179 LOG-1718: Vendor fluentd-plugin-detect-exceptions
  .gitignore
  fluentd/Gemfile
  fluentd/Gemfile.lock
  fluentd/fluent-plugin-detect-exceptions.source0001.patch
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/aws-eventstream/aws-eventstream.gemspec
  fluentd/vendored_gem_src/aws-partitions/aws-partitions.gemspec
  fluentd/vendored_gem_src/aws-sdk-cloudwatchlogs/aws-sdk-cloudwatchlogs.gemspec
  fluentd/vendored_gem_src/aws-sdk-core/aws-sdk-core.gemspec
  fluentd/vendored_gem_src/aws-sigv4/aws-sigv4.gemspec
  fluentd/vendored_gem_src/concurrent-ruby/concurrent-ruby.gemspec
  fluentd/vendored_gem_src/faraday/faraday.gemspec
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/CONTRIBUTING
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/Gemfile
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/LICENSE
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/README.rdoc
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/Rakefile
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/fluent-plugin-detect-exceptions.gemspec
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/lib/fluent/plugin/exception_detector.rb
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/lib/fluent/plugin/out_detect_exceptions.rb
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/test/helper.rb
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/test/plugin/bench_exception_detector.rb
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/test/plugin/test_exception_detector.rb
  fluentd/vendored_gem_src/fluent-plugin-detect-exceptions/test/plugin/test_out_detect_exceptions.rb
  fluentd/vendored_gem_src/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
  fluentd/vendored_gem_src/fluent-plugin-systemd/fluent-plugin-systemd.gemspec
  fluentd/vendored_gem_src/jmespath/jmespath.gemspec
  fluentd/vendored_gem_src/mime-types-data/mime-types-data.gemspec
  fluentd/vendored_gem_src/mime-types/mime-types.gemspec
  fluentd/vendored_gem_src/multi_json/multi_json.gemspec
  fluentd/vendored_gem_src/net-http-persistent/net-http-persistent.gemspec
  fluentd/vendored_gem_src/netrc/netrc.gemspec
  fluentd/vendored_gem_src/oj/oj.gemspec
  fluentd/vendored_gem_src/prometheus-client/prometheus-client.gemspec
  fluentd/vendored_gem_src/quantile/quantile.gemspec
  fluentd/vendored_gem_src/tzinfo-data/tzinfo-data.gemspec
  fluentd/vendored_gem_src/tzinfo/tzinfo.gemspec
  fluentd/vendored_gem_src/uuidtools/uuidtools.gemspec
Labels: lgtm, approved, release/5.3

#2178 LOG-1199: Allow log level for record to be set from message
  fluentd/lib/fluent-plugin-viaq_data_model/.gitignore
  fluentd/lib/fluent-plugin-viaq_data_model/Gemfile.lock
  fluentd/lib/fluent-plugin-viaq_data_model/fluent-plugin-viaq_data_model.gemspec
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model_systemd.rb
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_log_level_normalizer.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_log_level_normalizer.rb
Labels: lgtm, approved
