Repository openshift/origin-aggregated-logging, pull requests merged in 2021-12, with the labels that each got.

#2215 Bump ES binary to 6.8.1.redhat-00012 to mitigate CVE-2021-44228
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved, midstream/Dockerfile

#2216 Bump ES binary to 6.8.1.redhat-00012 to mitigate CVE-2021-44228
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved

#2217 Bug 2031028: Bump ES binary to 6.8.1.redhat-00012 to mitigate CVE-2021-44228
  elasticsearch/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#2218 Bug 2030985: Add log4j option to mitigate CVE-2021-44228
  elasticsearch/run.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent

#2221 Bump ES binary to 6.8.1.redhat-00013 to mitigate CVE-2021-45105
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved, midstream/Dockerfile

#2223 Bug 2034083: Bump ES 6.8.1.redhat-00013 to mitigate CVE-2021-45105
  elasticsearch/Dockerfile.rhel8
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#2222 [release-5.0] Bump ES binary to 6.8.1.redhat-00013 to mitigate CVE-2021-45105
  elasticsearch/Dockerfile.rhel8
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved

#2224 Log 2022: Updating resourceVersion attribute to a keyword
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
Labels: lgtm, approved
