Repository openshift/origin-aggregated-logging, pull requests merged in 2021-08, with the labels that each got.

#2158 LOG-1562: upgrade rubygem 'addressable' to the 2.0.8 version
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/addressable/CHANGELOG.md
  fluentd/vendored_gem_src/addressable/Gemfile
  fluentd/vendored_gem_src/addressable/README.md
  fluentd/vendored_gem_src/addressable/addressable.gemspec
  fluentd/vendored_gem_src/addressable/lib/addressable/idna/pure.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/template.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/uri.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/version.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/idna_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/rack_mount_compat_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/template_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/uri_spec.rb
  fluentd/vendored_gem_src/addressable/spec/spec_helper.rb
  fluentd/vendored_gem_src/addressable/tasks/gem.rake
  fluentd/vendored_gem_src/addressable/tasks/profile.rake
  fluentd/vendored_gem_src/addressable/tasks/rspec.rake
  fluentd/vendored_gem_src/aws-eventstream/aws-eventstream.gemspec
  fluentd/vendored_gem_src/aws-partitions/aws-partitions.gemspec
  fluentd/vendored_gem_src/aws-sdk-cloudwatchlogs/aws-sdk-cloudwatchlogs.gemspec
  fluentd/vendored_gem_src/aws-sdk-core/aws-sdk-core.gemspec
  fluentd/vendored_gem_src/aws-sigv4/aws-sigv4.gemspec
  fluentd/vendored_gem_src/concurrent-ruby/concurrent-ruby.gemspec
  fluentd/vendored_gem_src/faraday/faraday.gemspec
  fluentd/vendored_gem_src/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
  fluentd/vendored_gem_src/fluent-plugin-systemd/fluent-plugin-systemd.gemspec
  fluentd/vendored_gem_src/jmespath/jmespath.gemspec
  fluentd/vendored_gem_src/mime-types-data/mime-types-data.gemspec
  fluentd/vendored_gem_src/mime-types/mime-types.gemspec
  fluentd/vendored_gem_src/multi_json/multi_json.gemspec
  fluentd/vendored_gem_src/net-http-persistent/net-http-persistent.gemspec
  fluentd/vendored_gem_src/netrc/netrc.gemspec
  fluentd/vendored_gem_src/oj/oj.gemspec
  fluentd/vendored_gem_src/prometheus-client/prometheus-client.gemspec
  fluentd/vendored_gem_src/public_suffix/.github/workflows/tests.yml
  fluentd/vendored_gem_src/public_suffix/.rubocop_opinionated.yml
  fluentd/vendored_gem_src/public_suffix/.travis.yml
  fluentd/vendored_gem_src/public_suffix/CHANGELOG.md
  fluentd/vendored_gem_src/public_suffix/Gemfile
  fluentd/vendored_gem_src/public_suffix/codecov.yml
  fluentd/vendored_gem_src/public_suffix/data/list.txt
  fluentd/vendored_gem_src/public_suffix/lib/public_suffix/version.rb
  fluentd/vendored_gem_src/public_suffix/test/acceptance_test.rb
  fluentd/vendored_gem_src/public_suffix/test/psl_test.rb
  fluentd/vendored_gem_src/quantile/quantile.gemspec
  fluentd/vendored_gem_src/tzinfo-data/tzinfo-data.gemspec
  fluentd/vendored_gem_src/tzinfo/tzinfo.gemspec
  fluentd/vendored_gem_src/uuidtools/uuidtools.gemspec
Labels: approved, lgtm

#2160 LOG-1075: Update Prometheus plugin to custom release 6.8.1.1
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
Labels: approved, lgtm, midstream/Dockerfile

#2159 LOG-1071: CloudWatch fluentd plugin posts all logs it forwards to AWS to its own log
  fluentd/aws-sdk-core.source0001.patch
Labels: lgtm, approved

#2164 LOG-1680: Update roles in sgconfig
  elasticsearch/sgconfig/action_groups.yml
  elasticsearch/sgconfig/roles.yml
Labels: lgtm, approved

#2165 LOG-1657: Fixed admin_reader indices permissions
  elasticsearch/sgconfig/roles.yml
Labels: lgtm, approved

#2162 LOG-1646: Upgrade addressable to address CVE-2021-32740
  fluentd/Gemfile
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/addressable/CHANGELOG.md
  fluentd/vendored_gem_src/addressable/Gemfile
  fluentd/vendored_gem_src/addressable/README.md
  fluentd/vendored_gem_src/addressable/addressable.gemspec
  fluentd/vendored_gem_src/addressable/lib/addressable/idna/pure.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/template.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/uri.rb
  fluentd/vendored_gem_src/addressable/lib/addressable/version.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/idna_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/rack_mount_compat_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/template_spec.rb
  fluentd/vendored_gem_src/addressable/spec/addressable/uri_spec.rb
  fluentd/vendored_gem_src/addressable/spec/spec_helper.rb
  fluentd/vendored_gem_src/addressable/tasks/gem.rake
  fluentd/vendored_gem_src/addressable/tasks/profile.rake
  fluentd/vendored_gem_src/addressable/tasks/rspec.rake
  fluentd/vendored_gem_src/public_suffix/.github/workflows/tests.yml
  fluentd/vendored_gem_src/public_suffix/.rubocop_opinionated.yml
  fluentd/vendored_gem_src/public_suffix/.travis.yml
  fluentd/vendored_gem_src/public_suffix/CHANGELOG.md
  fluentd/vendored_gem_src/public_suffix/Gemfile
  fluentd/vendored_gem_src/public_suffix/codecov.yml
  fluentd/vendored_gem_src/public_suffix/data/list.txt
  fluentd/vendored_gem_src/public_suffix/lib/public_suffix/version.rb
  fluentd/vendored_gem_src/public_suffix/test/acceptance_test.rb
  fluentd/vendored_gem_src/public_suffix/test/psl_test.rb
Labels: lgtm, approved, release/5.1

#2163 fix for https://issues.redhat.com/browse/LOG-1647
  fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb
  fluentd/lib/fluent-plugin-collected/test/plugin/test_in_collected_tail_monitor.rb
Labels: lgtm, approved
