Repository openshift/origin-aggregated-logging, pull requests merged in 2021-03, with the labels that each got.

#2074 Update hack/deploy-logging.sh to use CI env vars
  hack/deploy-logging.sh
Labels: approved, lgtm

#2064 Bug 1930360: fluentd is unable to send logs to Elasticsearch because it can't authenticate to the es-proxy
  fluentd/Dockerfile
  fluentd/Dockerfile.centos7
  fluentd/run45.sh
  test/unit/Dockerfile
  test/unit/run.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2073 Fixed typo in out_syslog, TCP & UDP. Global @facilty should be @facility
  fluentd/out_syslog.rb
  fluentd/out_syslog_buffered.rb
Labels: approved, lgtm, ok-to-test

#2051 Update fluentd README to include hack instructions
  fluentd/README.md
Labels: approved, area/documentation, lgtm, release/4.7

#2072 Create README.md for this doc directory
  docs/README.md
Labels: approved, lgtm, ok-to-test

#2053 [LOG-334] Setup cgroups path override to enable cgroups metrics
  elasticsearch/run.sh
Labels: approved, lgtm

#2068 Bug 1904380 - Forwarding logs to Kafka using Chained certificates fals with error "state=error: certificate verify failed (unable to get local issuer certificate)
  fluentd/fluent-plugin-kafka.source0002.patch
Labels: approved, lgtm

#2094 Setting python alternatives to python3
  elasticsearch/Dockerfile.origin
Labels: approved, lgtm

#2090 Rebuild elasticsearch to bump the version jackson dependency
  elasticsearch/Dockerfile.origin
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/install-es.sh
Labels: approved, lgtm
