Repository openshift/origin-aggregated-logging, pull requests merged in 2021-06, with the labels that each got.

#2127 Updating sg roles_mapping to allow for updated cert O and OU
  elasticsearch/run.sh
  elasticsearch/sgconfig/roles_mapping.yml
Labels: approved, lgtm

#2130 Bug 1883902: Adding COPY line to Dockerfile.rhel8 to be in sync with Dockerfile
  kibana/Dockerfile.rhel8
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2122 LOG-1195: Add Openshift Ingest Plugin for ES
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/ingest_pipelines/openshift_schema.json
  elasticsearch/init/0100-seed-pipelines
  elasticsearch/init/0200-seed-index-templates
  elasticsearch/install.sh
Labels: approved, lgtm, midstream/Dockerfile

#2132 Bug 1849504: vendoring in minimist 1.2.5
  kibana/Dockerfile
  kibana/Dockerfile.rhel8
  kibana/vendored_tar_src/minimist/.travis.yml
  kibana/vendored_tar_src/minimist/LICENSE
  kibana/vendored_tar_src/minimist/example/parse.js
  kibana/vendored_tar_src/minimist/index.js
  kibana/vendored_tar_src/minimist/package.json
  kibana/vendored_tar_src/minimist/readme.markdown
  kibana/vendored_tar_src/minimist/test/all_bool.js
  kibana/vendored_tar_src/minimist/test/bool.js
  kibana/vendored_tar_src/minimist/test/dash.js
  kibana/vendored_tar_src/minimist/test/default_bool.js
  kibana/vendored_tar_src/minimist/test/dotted.js
  kibana/vendored_tar_src/minimist/test/kv_short.js
  kibana/vendored_tar_src/minimist/test/long.js
  kibana/vendored_tar_src/minimist/test/num.js
  kibana/vendored_tar_src/minimist/test/parse.js
  kibana/vendored_tar_src/minimist/test/parse_modified.js
  kibana/vendored_tar_src/minimist/test/proto.js
  kibana/vendored_tar_src/minimist/test/short.js
  kibana/vendored_tar_src/minimist/test/stop_early.js
  kibana/vendored_tar_src/minimist/test/unknown.js
  kibana/vendored_tar_src/minimist/test/whitespace.js
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2131 Vendoring in minimist 1.2.5
  kibana/Dockerfile
  kibana/Dockerfile.in
  kibana/vendored_tar_src/minimist/.travis.yml
  kibana/vendored_tar_src/minimist/LICENSE
  kibana/vendored_tar_src/minimist/example/parse.js
  kibana/vendored_tar_src/minimist/index.js
  kibana/vendored_tar_src/minimist/package.json
  kibana/vendored_tar_src/minimist/readme.markdown
  kibana/vendored_tar_src/minimist/test/all_bool.js
  kibana/vendored_tar_src/minimist/test/bool.js
  kibana/vendored_tar_src/minimist/test/dash.js
  kibana/vendored_tar_src/minimist/test/default_bool.js
  kibana/vendored_tar_src/minimist/test/dotted.js
  kibana/vendored_tar_src/minimist/test/kv_short.js
  kibana/vendored_tar_src/minimist/test/long.js
  kibana/vendored_tar_src/minimist/test/num.js
  kibana/vendored_tar_src/minimist/test/parse.js
  kibana/vendored_tar_src/minimist/test/parse_modified.js
  kibana/vendored_tar_src/minimist/test/proto.js
  kibana/vendored_tar_src/minimist/test/short.js
  kibana/vendored_tar_src/minimist/test/stop_early.js
  kibana/vendored_tar_src/minimist/test/unknown.js
  kibana/vendored_tar_src/minimist/test/whitespace.js
Labels: approved, lgtm, midstream/Dockerfile

#2135 fix smoke test to use 5.1
  Makefile
  hack/deploy-logging.sh
Labels: approved, lgtm

#2136 fix smoke test to proper version
  Makefile
  hack/deploy-logging.sh
Labels: approved, lgtm

#2134 LOG-1195: Add Openshift Ingest Plugin for ES
  HACKING.md
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/ci-env.sh
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/ingest_pipelines/openshift_schema.json
  elasticsearch/init/0100-seed-pipelines
  elasticsearch/init/0200-seed-index-templates
  elasticsearch/install.sh
Labels: approved, lgtm, midstream/Dockerfile, release/5.1

#2137 Enable MAVEN_REPO_URL for the ingest plugin
  elasticsearch/ci-env.sh
Labels: approved, lgtm

#2141 Update ingest plugin version
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/fetch-artifacts-koji.yaml
Labels: midstream/Dockerfile
