Repository openshift/origin-aggregated-logging, pull requests merged in 2022-05, with the labels that each got.

#2253 Bug 2086496: Align prom-exporter version between CI and downstream
  elasticsearch/Dockerfile.rhel8
  elasticsearch/ci-env.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#2254 Add Jaeger auth for dependencies index
  elasticsearch/sgconfig/roles.yml
Labels: lgtm, needs-ok-to-test, approved

#2255 Bug 2091584: Add Jaeger auth for dependencies index
  elasticsearch/sgconfig/roles.yml
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
