Repository openshift/origin-aggregated-logging, pull requests merged in 2022-01, with the labels that each got.

#2227 LOG-2098 Remove bundler from logging fluentd image
  fluentd/Dockerfile
  fluentd/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile

#2225 Log 2089: Updating resourceVersion attribute to a keyword
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: lgtm, approved

#2228 Correction to the fix for LOG-1315: place ua-parser-js-1.0.2 under node_modules/ua-parser-js
  kibana/Dockerfile
  kibana/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile

#2226 Bug 2034412: Updating resourceVersion attribute to a keyword
  docs/com.redhat.viaq-openshift-operations.asciidoc
  docs/com.redhat.viaq-openshift-project.asciidoc
  docs/org.ovirt.viaq-collectd.asciidoc
  elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-operations.template.json
  elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json
  elasticsearch/index_templates/org.ovirt.viaq-collectd.template.json
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#2229 LOG-2119: Add required permission to sg_role_curator for delete by query
  elasticsearch/sgconfig/action_groups.yml
  elasticsearch/sgconfig/roles.yml
Labels: lgtm, approved

#2230 LOG-2102: Update ES to include log4j v2.17.1 to fix CVE-2021-44832
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved, midstream/Dockerfile

#2231 LOG-2103: Update ES to resolve CVE-2021-44832
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved

#2232 [release-4.6] Bug 2036040: Update ES to resolve CVE-2021-44832
  elasticsearch/Dockerfile.rhel8
  elasticsearch/fetch-artifacts-koji.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#2233 LOG-1923:Fix username according to the subject in certificates
  elasticsearch/sgconfig/config.yml
  kibana/kibana.yml
Labels: lgtm, approved

#2235 Revert "LOG-1923:Fix username according to the subject in certificates"
  elasticsearch/sgconfig/config.yml
  kibana/kibana.yml
Labels: lgtm, approved

#2236 Bug 2036043: fix component images to unblock builds
  curator/Dockerfile.centos7
  fluentd/Dockerfile.centos7
Labels: approved

#2234 Bug 2036043: Fix CVE-2021-44832 to upgrade log4j version to 2.17.1
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.centos7
  elasticsearch/elasticsearch.repo
  elasticsearch/extra-jvm.options
  elasticsearch/fetch-artifacts-koji.yaml
  elasticsearch/install.sh
  elasticsearch/prep-install.origin
  elasticsearch/prep-install.prod
Labels: approved, bugzilla/valid-bug, bugzilla/severity-medium

#2237 Disable fips mode to deploy elasticsearch on a fips enabled cluster
  elasticsearch/Dockerfile
  elasticsearch/Dockerfile.in
Labels: lgtm, approved, midstream/Dockerfile
